### ISSUE TITLE
Fill <links> element in schedule.xml

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#1001]
## Problem you are facing
- The `<links>` element in the generated _schedule.xml_ is empty.
- Links are not filled with content in the [agenda template](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/templates/agenda/schedule.xml#L39).
- Example from [Pretalx generated DiVOC schedule XML](https://talks.mrmcd.net/ptt/schedule/export/schedule.xml):

``` xml
<event guid="8abb9efc-3c12-5a88-b1dd-e721705d3095" id="238">
	<date>2020-09-04T18:00:00+02:00</date>
	<start>18:00</start>
	<duration>00:15</duration>
	<room>Schneider-Hoover</room>
	<slug>ptt-238-opening</slug>
	<url>https://talks.mrmcd.net/ptt/talk/CKHNL9/</url>
	<recording>
		<license/>
		<optout>false</optout>
	</recording>
	<title>Opening</title>
	<subtitle/>
	<track/>
	<type>Short and sweet</type>
	<language>de</language>
	<abstract>Opening</abstract>
	<description>Opening *Stell deine Fragen zum Talk [in diesem Pad](https://di.c3voc.de/pad/ptt:talk:CKHNL9).*</description>
	<logo/>
	<persons>
		<person id="212">N.N.</person>
	</persons>
	<links/>
	<attachments/>
</event>
```

## Possible Solution
- Add form field to enter links if it is not already present.
- Example from [aggregated DiVOC schedule XML](https://data.c3voc.de/divoc/schedule.xml):

``` xml
<event guid="b4e214e6-9d25-5a7b-8019-9d9a1b18e7f0" id="1000">
	<date>2020-09-04T18:00:00+02:00</date>
	<start>18:00</start>
	<duration>2:00</duration>
	<room>Self-organized</room>
	<slug>divoc3-1000-english_haecksenbreakfast</slug>
	<url>https://di.c3voc.de/sessions-liste</url>
	<title>English Haecksenbreakfast</title>
	<subtitle/>
	<track>Workshop</track>
	<type>Workshop</type>
	<language>de</language>
	<abstract>We invite all creatures of any and all genders to come and say hello</abstract>
	<description/>
	<persons>
		<person id="0">mapc (Haecksen)</person>
	</persons>
	<links>
		<link>https://meeten.statt-drosseln.de/b/kar-pgn-nrt</link>
	</links>
</event>
```

## Context
- Separating links allows the [_EventFahrplan_ App](https://github.com/EventFahrplan/EventFahrplan) to comfortably parse and render links as a separate section in the UI.

**Comment by rixx** [comment]
Since there is currently no way to attach separate links to sessions in pretalx, we have nothing that we can export there.

**Comment by johnjohndoe** [comment]
Would you consider adding a form field for the session author(s) to enter links such as project url, slides, ...?

**Comment by rixx** [comment]
They can currently upload slides, but I don't see much use for fields for arbitrary links, when they could add them just as well to the description, with more flexibility in format (like adding headings or sub-points or clarifications etc). Maybe I'm missing something?

**Comment by johnjohndoe** [comment]
> ... with more flexibility in format (like adding headings or sub-points or clarifications etc)

I am not informed about the current input design. Is it correct that users can use markdown to format their session description?
Is the markdown changed in any way or does it show up as entered in the XML export?

**Comment by n-st** [comment]
@rixx A separate input for links would allow schedule.xml consumers (like @johnjohndoe's Android app) to show links in a separate area or formatting, which could improve end-user experience.

I couldn't find a canonical source about the schedule.xml format, but it seems that links can also be given a title, like this?

    <links>
        <link href="http://example.com">A very useful website</link>
    </links>

**Comment by n-st** [comment]
@johnjohndoe The "abstract" and "description" texts are currently included in the schedule.xml "as-is" (without Markdown rendering, but escaping special characters as HTML/XML sequences):

https://github.com/pretalx/pretalx/blob/716158816c54b504ce25cadb8b2bcae54ebfbcf3/src/pretalx/agenda/templates/agenda/schedule.xml#L33-L34

It might be possible to render the Markdown to HTML like this, then xmlescape the resulting HTML afterwards?

https://github.com/pretalx/pretalx/blob/716158816c54b504ce25cadb8b2bcae54ebfbcf3/src/pretalx/agenda/templates/agenda/talk.html#L70-L72

**Comment by n-st** [comment]
Apropos fields in the schedule.xml: The "attachments" node is currently hardcoded empty in the template. Are the slide uploads included in the schedule.xml in some other way? Should they be moved or duplicated to the "attachments"?

https://github.com/pretalx/pretalx/blob/716158816c54b504ce25cadb8b2bcae54ebfbcf3/src/pretalx/agenda/templates/agenda/schedule.xml#L40

Sorry for just dumping all this here, I hope I'll be able to contribute more productively after our current event is finished.

**Comment by johnjohndoe** [comment]
Here is what currently is applied to content in the `abstract` and `description` and `links`* field: [StringUtils.java](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/java/nerd/tuxmobil/fahrplan/congress/utils/StringUtils.java).

_*some preprocessing happens_

**Comment by rixx** [comment]
Slide uploads are not currently included in the schedule.xml export. PRs are welcome – but the schedule.xml format is a compatibility format that we maintain mostly towards community integrations, and not something that I can (or want to) sink major time into.

Background (mostly for @n-st because of your question for a canonical source): The schedule.xml format is originally a product of the conference management tool `pentabarf`. Its successor, [frab](https://github.com/frab/frab) continued to use and expose it, with only minor changes. Due to these two tools, an ecosystem grew around the format, such as `EventFahrplan`, or lots of the VOC video processing pipeline. Thankfully, VOC also maintains a schedule.xslt [validation file](https://c3voc.de/schedulexml/), mostly to make sure that other data sources are transformed correctly. pretalx continuously tests its export against the latest version of that validator.

**However.** Frab is, as far as I can tell, currently maintained on an intermittent bugfix basis: PRs are merged after variable waiting times, but there is no active feature development. This makes it extremely hard to make any adjustments to the schedule.xml format – even our cooperative move to include a `generator` tag (to make it easier for `EventFahrplan` and other tools to handle the data) took over a year and resulted in a period of at least six months where the XSLT was not in sync with frab and pretalx.

Given frustrating experiences like that, my stance towards the frab compatible exports comes down to this: I won't break them intentionally, and I'm keeping them in working order – mostly because otherwise the pretalx tests would yell at me, and I don't want to upset them. Tests are dangerous when angry. But any other extension or maintenance is up to the community actually using these tools and interfaces. pretalx has – for some time now – outgrown the limitations of the `schedule.xml` format, and expanding its technical and social constraints does not seem viable at this time.

**Comment by johnjohndoe** [comment]
@rixx Thank you for writing down the contextual information. Also, I wasn't aware of the XML web validator - thanks for sharing.
I appreciate your efforts and understand that maintaining or extending the XML export format must have its limits.
