### ISSUE TITLE
Unable to add to Team??  

### ISSUE THREAD

**Issue by mraugh** [pretalx/pretalx#1020]
## Current Behavior
A new instance of v1.2, on Ubuntu.  I am unable to add staff members.  I've tried entering a name and email address, but no email gets sent to them.  I can click the link next to the email and "Join This Team" but all it does is delete the user from the team.

## Expected Behavior
Either an email goes out to that address and the user can respond, or I can click the link and press Join This Team and it adds them to the team, asking for a password.

## Steps to Reproduce

1. Log in
2.Click Teams
3. Choose any team from the list
4. Add an email address

## Context

This is keeping me from adding anyone else to the team, which is going to be a drag very soon.

## Your Environment

Pretalx v1.2
On Ubuntu 20.04
Python 3.8.5
Any browser or client OS
https://pretalx.charmedhypno.org

<MR>

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by mraugh** [comment]
I should have mentioned that emails do work otherwise; I have other people who've logged in and contributed proposals with no problem.  I don't really care if email works as long as I can create the team users manually -- there's only a couple.

**Comment by rixx** [comment]
First off, email sending for team emails works differently from event emails, since teams don't belong to any event. You'll have to check your instance email settings.

Secondly, the "join this team" link is meant for the receiving user, not for your currently logged in user. When you follow the link, the invite is deleted since you have accepted it. So you should hand this link to the person you want to invite.
