### ISSUE TITLE
Unable to enter tags

### ISSUE THREAD

**Issue by mjang** [pretalx/pretalx#1049]
## Current Behavior

Unable to set up tags in the following screen:

![Screenshot from 2021-01-31 13-04-29](https://user-images.githubusercontent.com/3287976/106398032-6dfdf880-63c5-11eb-8e8a-faf544b914ab.png)

I can't type anything in the text boxes, or in the "Show tag publicly" checkbox. When I select "Save", I get an error message: "You are trying to change read-only data"

## Expected Behavior

Successfully create a tag to link to various proposals

## Steps to Reproduce

1. Select Tags in the left-hand menu
2. Click New Tag
3. Try to type in whatever.
4.

## Your Environment

Ubuntu 16.04

- Chrome Version 88.0.4324.96 (Official Build) (64-bit)
- Firefox 84.0.2

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
Creating tags is restricted to people who can either edit proposals, or who are reviewers while the active review phase permits the creation tags.

We should hide the link to the tag creation page in that case, though.

**Comment by mjang** [comment]
I am an active reviewer in this particular CfP.

It sounds like this is a legit bug. Why did you close it?

**Comment by rixx** [comment]
I closed the bug because I wrote a fix that hides the link to the tag creation page if the user does not have access rights, so nobody will come across the useless page you showed above. As this fixes the immediate problem, I consider the issue closed.

Can you confirm that in your event's review settings (pictured below) the permission is "add, remove **and create**" tags? In that case, I will re-open the issue, but otherwise, pretalx works as intended.
![DeepinScreenshot_select-area_20210131232820](https://user-images.githubusercontent.com/2657547/106399986-1474e880-641c-11eb-80a6-c09b13023e9d.png)

**Comment by plaindocs** [comment]
Looks like a bug to me. Although I wonder if it could be tangled up in the previous "can see other reviews" setting? 

![image](https://user-images.githubusercontent.com/95874/106436350-487bf800-6474-11eb-96ff-022b615371a3.png)

**Comment by plaindocs** [comment]
Just adding context, as full permissions admin I can add tags and tag talks 

(Off topic, would be nice to see tags in list view)
