### ISSUE TITLE
Manage user access for some events

### ISSUE THREAD

**Issue by gebi** [pretalx/pretalx#1058]
## Problem you are facing
As we know and love pretalx from our open source work we wanted to use it to create events that are not publicly accessible.
So have a list of users that are able to access all public events and some of the not publicly accessible events they have access to.

## Possible Solution
Make people register for an event and provide access permissions to some events.

## Context

the workflow of pretalx also fits really nicely for some internal things, and for some not publicly accessible events too.
Thus we search for configuration in pretalx for some events being only accessible to a subset of users, though could not find anything in that regard.
Maybe we are just missing the obvious way via some django parts, or have just searched in the wrong place.

Any pointers ideas would be greatly appreciated

**Comment by rixx** [comment]
There's no way to do that at the moment. There are workarounds: You can turn off the public schedule, and use the widget in a private place, for example. Or you could add everybody who should have access to the event organiser team and just never make the event public at all.

**Comment by rixx** [comment]
Having thought about it a bit more, I think this is for the moment out of scope for pretalx, since pretalx does not manage attendees/attendee accounts at all. If you want to use pretalx for something like it, I'd recommend handling the authentication at some other level (corporate VPN, Basic Auth) and either embedding the pretalx widget or using the HTML export.
