### ISSUE TITLE
Configurable day change

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#1089]
Sessions are sorted into the individual event days. An event day does not necessarily end at 00:00 but might extend until 04:00am. Sometimes sessions for that day last longer - mostly when DJs are involved.

Therefore, the question: Is the day change configurable for people who set up the schedule content?

# Related
- https://github.com/pretalx/pretalx/blob/287a4dc5a1f008878f5f7926f360b3f3ccf68ce9/src/pretalx/schedule/exporters.py#L58

**Comment by rixx** [comment]
This only concerns the frab exporter, right? This seems like a problem inherent to the design choice of a nested format (`<day><room><talk>`) instead of just providing flat lists.

I'm a bit hesitant to add yet another setting just for an external interface like that … maybe it's time to move the frab exporter into a separate plugin.
If somebody were to contribute this as a feature to pretalx, I'd probably merge it, though I wouldn't be particularly happy about it.

**Comment by johnjohndoe** [comment]
> This only concerns the frab exporter, right? This seems like a problem inherent to the design choice of a nested format (`<day><room><talk>`) instead of just providing flat lists.

Good point. I will check if it makes sense to ignore the nested format altogether and let the client app decide when the day change happens.

> I'm a bit hesitant to add yet another setting just for an external interface like that … maybe it's time to move the frab exporter into a separate plugin.
> If somebody were to contribute this as a feature to pretalx, I'd probably merge it, though I wouldn't be particularly happy about it.

Understandable. It's on the list to migrate the client app but hard to accomplish with low human resources.

I think we can close here for now. Thank you.
