### ISSUE TITLE
Allow to send mails to speakers with (specific) unanswered questions

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#115]
"Send this template to all speakers who have not given their arrival date."

The cooler version of this allows to send mails to speakers **depending on their answer**, including an answer of "no answer yet".

**Comment by luto** [comment]
There is a WIP of this in [`115-send-email-based-on-questions`](https://github.com/pretalx/pretalx/tree/115-send-email-based-on-questions). It is able to correctly generate the needed forms and provides some infrastructure needed for this feature. Since I can't wrap my head around the Django ORM enough right now to actually generate the needed list of speaksers based on the selected answers, I am throwing this one back into the pond.

Anyone, feel free to grab this. In case you are just interested in the heavy lifting, I am more than happy to do the dirty work of previewing and sending out mails assuming there is a list of speakers to send them to.
