### ISSUE TITLE
Small browser view (f.e. mobile) is constantly flabbering

### ISSUE THREAD

**Issue by cambid** [pretalx/pretalx#1170]
## Current Behavior

The view of the schedule on mobiles, tablets and small browsersize is flabbering constantly and the talks in the two rooms are overlapping if the event is running for more than three days.

## Expected Behavior

No flabbering in the mobile and small browser view without overlapping talks.

## Steps to Reproduce

1. create a test event: python manage.py create_test_event --stage=schedule
2. expand the event to five or more days via settings
2. Create a schedule with sessions on more than three days and publish it.
3. Open the schedule on a mobile phone or tablet.

## Your Environment

* Version used: latest git checkout 0543317da1a0d9b75ff43b38886a4c37a4694e76
* Environment name and version (e.g. Chrome 39, python 3.5): python 3.9.7 for pretalx. Firefox or Chrome on Android or default browser on iPhone. I can also reproduce the issue by resizing a normal Firefox window enough.
* Operating System and version (desktop or mobile): mobile and desktop.
* Link to your instance, if in production: https://fahrplan.privacyweek.at/pw21/

**Comment by cambid** [comment]
@MacLemon Can you comment the used version of pretalx at fahrplan.privacyweek.at, please?

**Comment by rashfael** [comment]
There seems to be feedback loop in the resize observer for automatically changing from grid to list and vice versa. Looks like with a large amount of days the tab header is larger than the threshold, the list view expands the container above the threshold again, causing a switch back to the grid view. Since we need the whole container to be able to expand, to make wide schedules horizontally scrollable, we can't just simply `min-width: 0` the whole thing. Thankfully, we already solved this for the grid view.

**Comment by cambid** [comment]
@all: Thanks for the fix. I tested it and can confirm that it is working.
