### ISSUE TITLE
Add "advanced search" to /reviews

### ISSUE THREAD

**Issue by RichiH** [pretalx/pretalx#1183]
I usually group ratings by type of submissions, i.e. all lightning talks at once. Being able to filter by "lightning talks; not rated by me yet" would be nice.

Along similar lines, I would like to sort on all fields, not just "Your Score" and "Reviews".

While I submitted this for `/reviews/` only, the same request is applicable for all other backend data views.

**Comment by rixx** [comment]
Thanks for the feedback! I changed the title of the issue because I'm already not terribly happy with the filters at the top of the page – I think introducing an "advanced search" page (or hidden section) would go a long way to make it easier to add filters like "rated by me". The current "number of reviews" filter would probably go there, too.

**Comment by RichiH** [comment]
Agreed, putting all that into an advanced search works nicely.

Just don't forget the sorting of ALL the things (or should I create a new issue to track that?)

**Comment by rixx** [comment]
Nah, it's fine – as soon as the frontend rewrite starts, fixing/adding the sorting will be somewhat free. Hopefully soon™!

**Comment by rixx** [comment]
Merging into #1618 to keep all the filters we want to add in one place.
