### ISSUE TITLE
Ability to add new Question types

### ISSUE THREAD

**Issue by freloe** [pretalx/pretalx#1225]
We wanted to use pretalx for an application type website, we already changed the cfp abit but it would be great if we could add more question types. If that isn't a wanted feature it would still be great to know how you implemented the question types so we could change that on our own.

**Comment by rixx** [comment]
We can't add new question types in the frontend, if that's what you mean, because question types include all of a widget, validation, serialisation and deserialisation. But we can definitely include more question types in future pretalx updates.

To that end, we would need to discuss *which* question types you're missing, though.

**Comment by freloe** [comment]
Thank you for your quick answer, we wanted to add horizontal radio select (for rating something) and possibly something like a country select or dropdown select.

**Comment by rixx** [comment]
Radio selects are already possible – placing them horizontally is a CSS issue that you can just address with custom event CSS. Radio buttons are used for all choice questions with up to three options, as more options make radio selects clumsy and harder to navigate

Dropdown selects, which you also want, are then used for choice questions with more than three options, so this would come into play if you use your mentioned country select.
