### ISSUE TITLE
Per-speaker emails

### ISSUE THREAD

**Issue by britiger** [pretalx/pretalx#1244]
## Current Behavior

There is no more To field in Mail Editor #1178 so it is unable to send a mail to a single speaker over pretalx. The link on speakers page is unusable and wrong. You also need to select a submission there the speaker is the only one. We also have speakers which are not. 

## Expected Behavior

Possibility to send mails to a single speaker. 

## Steps to Reproduce

1. Choose a speaker in list of speakers (`https://pretalx.com/orga/event/<event>speakers/<speaker_id>/`)
2. Click on link to compose an individual mail to this speaker on bottom
3. Mail Editor will be opened, the link is formatted `https://pretalx.com/orga/event/<event>/mails/compose?email=<user>@<doamin>`
4. On Mail Editor there is no field for "To", so the given parameter is not used
5. Fill out subject and body
5. If click on preview / send there will be generate mails for **all** speakers

## Context

As  solution we need to generate a dummy-mail in outbox and change the speaker while editing the mail. If I edit a mail I found the To field where I can fill out the single Speaker or a non registered speaker.

## Your Environment

* German language
* Link to your instance, if in production: pretalx.com (Event: fossgis2022)

**Comment by rixx** [comment]
Yes, pretalx can currently only send emails in the context of a talk or a proposal – this was a necessary cost of allowing template variables such as "{title}" or "{start}". This was an extremely highly requested feature, so that we judged it to be more important than individual-speaker level emails.

We're aiming to add a feature to switch between "talk-based" and "speaker-based" emails in the future, and I'll keep this issue open as a feature request in this direction. I'll remove the broken link to speaker-level emails in the meantime.

**Comment by vmx** [comment]
@rixx Is sending per speaker emails not possible UI wise, or also due to the internals?

Background why I'm asking this. For the FOSSGIS conference last year, I created a bash script that queued up custom emails. It was a [crude hack](https://github.com/vmx/conference-tools/blob/5c04deb38a5ccf1e7e4ad2c61f46b5c7dcc46343/email_speaker_final/email_to_pretalx.sh), where I copied the tokens I needed from the Firefox Web Console. Back then I already wondered, would it make sense to have an API endpoint for sending custom emails?

Back to this issue. Would it be possible to create such an endpoint today, that would enable sending custom emails to individual speakers? Or would bigger internal changes be needed? I think I could provide a PR for the endpoint, but probably not if major internal things need to change.

**Comment by rixx** [comment]
The underlying data structure of `QueuedMail` objects has not changed, so creating individual emails via a script is still possible.

**Comment by n-st** [comment]
Would it be possible to remove the "Compose mail" button on speaker profiles for now, or ideally replace it with an information text explaining that the UI can currently only send emails per proposal, not per speaker?

I'm asking because I very nearly sent an email to all speakers of an event after confidently clicking the "Compose mail" button on one speaker profile (and even checking that the `?email=…` GET parameter was still intact in the mail form URL)… :speak_no_evil:
