### ISSUE TITLE
Email variable bug

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1286]
## Current Behavior

Mouse over shows a different talk title instead of speaker name 

## Expected Behavior

It's not clear whether variables examples in mousehover are all relevant to this conf. Event name and slug are. `{speakers}` says it is "Open architected uniform middleware", likewise `{proposal_title}` (but it isn't).

~I'll confirm if the email preview looks ok.~ Definitely a bug. 

![image](https://user-images.githubusercontent.com/95874/157479937-843362b3-473f-4355-99ba-3bcf5fba5057.png)

## Steps to Reproduce

1. Compose email
2. Mouseover variables

**Comment by rixx** [comment]
Thankfully that's only a bug in the example rendering, the actual emails would have been rendered with the speaker names.

The examples are not all actually taken from the event, because finding a representative example is really hard! Just using a random talk could end up with one without speakers, or one with ten speakers, and so on.

**Comment by plaindocs** [comment]
Haha, excellent. Is it worth colour coding what is real content from this conf, and what is example content in a similar shape?

**Comment by rixx** [comment]
(As a side note, for a greeting, you'll want to use `{name}`, not `{speakers}`).

I'm not sure colour coding would help – feels like it would just confuse? I'd rather move to even more obvious placeholders like "This Is a Session Title" …
