### ISSUE TITLE
Breaks not included in schedule API

### ISSUE THREAD

**Issue by samipe** [pretalx/pretalx#1366]
### Problem and impact

Breaks are not included in the schedule. Based on reading test code in Breaks-commit #806 it seems they should be included? 

Not sure if related, but custom domain seems to cause some unexpected behaviour in API:
- https://cfp.robocon.io/robocon-2023/schedule/export/schedule.json 
Contains talks nested deep in conference > days > rooms > roomName -- but no breaks
- https://cfp.robocon.io/api/events/robocon-2023 and https://pretalx.com/api/events/robocon-2023
Returns 301

### Expected behaviour

Include breaks and their description in schedule or some other endpoint. Also there's no documentation mentioning them.

### Steps to reproduce

1. https://cfp.robocon.io/robocon-2023/schedule/export/schedule.json
2. Talks shown, breaks not

**Comment by rixx** [comment]
You are correct that breaks are not currently included in exports, as these exports are only meant for *proposals* and their associated metadata. Breaks lack some data that the API schema of the `schedule.json` format demands, such as stable IDs, speakers, content and so on. For the same reason, breaks are not included in the `/submissions/` API.

There is an API endpoint at `/schedules/`, or rather `/schedules/<version>/`, which includes breaks. This endpoint is currently *intentionally undocumented* because I'm not yet sure it is stable. It's bad enough that the `/submissions/` API will probably sooner or later go through some breaking changes, and I'd like to break as few API promises as possible. You should be able to use this endpoint to retrieve your entire current schedule at [`/schedules/latest/`](https://pretalx.com/api/events/robocon-2023/schedules/latest/), though.

I suppose we could add a `/breaks/` API endpoint, but I do not believe anybody would be particularly happy with that solution. (I would merge a PR to that effect, though.)

**Comment by rixx** [comment]
Closing in favour of #1367, but anybody with additional ideas on schedule handling: feel free to comment or re-open.
