### ISSUE TITLE
Prevent all scores from being marked as independent

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1387]
Pretalx doesn't deal well when all score categories are independent – and it doesn't make that much sense: independent from what? The total score is then shown as always zero, which is confusing and pointless.

**Comment by rixx** [comment]
Go for it!

**Comment by Pradhvan** [comment]
Apologies for the later reponse on the isssue. 

I cloned the project and played around with it locally. 

Got an understanding of  what an independent review is, how an org memember can created a ReviewScoreCategory that is independent and  how it shows up as their own column in the review dashboard.

The approach I am confused is with having a query like  

```Python
# Check if any previously saved score category has at least one category that has is_independent=False

ReviewScoreCategory.objects.exclude(pk=self.pk).filter(is_independent=False, event=self.event).exists()
```

1. Either in the `save()` of `ReviewScoreCategory` model. Should I raise an exception when it does not find an independt review ?

2. Or have it as a method so that it can be called in the `views.py::EventReviewSettings()::def save_scores()`` method where we save score.

Since deleting a score category is handeled in seprate API call which calls `ScoreCategoryDelete` we would have to update that class too. 

#### Things I tried locally

* Added the query mentioned above in the both model's save() and delete method. 
* Tested the approach in createting paris of independent score category and normal score categorys. Deleting one normal score category, keeping only independent. Trying to delete the idependent one in the pair. 

Though looks like I might be missing something in my logic.  

Just want some pointers on how to move forward, @rixx if you get some time can you briefly look at this and point to the right direction.Thank you. 😄

**Comment by rixx** [comment]
That's looking pretty good to me! I think the puzzle piece you're missing is that the logic is probably best placed in `ScoreCategory.delete()`. I think raising a `ValidationError` would be best here, which we can then expose in forms, views and APIs equally.

(hope that's helpful! it really looks like you're mostly done already :smile:  )
