### ISSUE TITLE
Add `/tracks` endpoint to REST API

### ISSUE THREAD

**Issue by saerdnaer** [pretalx/pretalx#1399]
### Problem and impact

I'd like to query the tracks of an event including their settings like color etc. via the REST API

### Proposed solution / feature

* Add route `GET /api/events/{event}/tracks`
* Add tracks list to `/api/events/{event}/schedules/latest/` response

ideally both

**Comment by rixx** [comment]
Agreed on the `/tracks` endpoint – that would be nice to have and easy to add, happy to merge a PR to that extent.

Tracks are already included in the `/schedules` endpoint, embedded in the slots data. I don't believe adding more top level attributes would be good for that endpoint (apart from the fact that I dearly wish to refactor it entirely – might have a breaking API change there in 3.0 or 4.0).

**Comment by saerdnaer** [comment]
I checked the `/schedules` endpoint at https://pretalx.c3voc.de/api/events/fire-shonks-2022/schedules/latest/:

it only contains the track names and id, but not the color:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/40266/209244078-ad6aaa13-639c-4bdd-8e6f-c2004a864b75.png">

**Comment by rixx** [comment]
Yes, that's true, and like I said, adding a `/tracks/` endpoint to retrieve that information is a good idea. Embedding all information, in this case repeatedly, in the `/schedules/` endpoint would be pretty terrible imo. Open to be convinced, but sceptical.

(I prefer the data format of the widget endpoint, and since the `/schedules/` endpoint was purposefully never documented to avoid forming a binding API, we may replace it with the widgets format at some point entirely.)

**Comment by rixx** [comment]
Folded into the Writable API issue (#1598 )
