### ISSUE TITLE
Reviews endpoint does not return user name and e-mail like defined in the API Docs

### ISSUE THREAD

**Issue by FlorianWilhelm** [pretalx/pretalx#1416]
### Problem and impact

Querying the endpoint `/api/events/{event}/reviews`,  the returned JSON has for the field `user` only the user name as string. According to the docs https://docs.pretalx.org/api/resources/reviews.html it should be an object/dictionary having also an e-mail address. 

This is a severe bug if someone wants to join this data with external data where the common field is often the e-mail address.

### Expected behaviour

The expected behaviour is that the `/api/events/{event}/reviews` returns a field `user` that is an object encompassing `name` **and** `email`. Like defined in the docs:

![image](https://user-images.githubusercontent.com/3184072/212537118-4102db90-a2a8-4fcb-92eb-3ef8c10fb70b.png)

### Steps to reproduce

1. Query the endpoint `/api/events/{event}/reviews`
2. Check the result JSON
3. Notice that `user` has the wrong type and no e-mail is available.

### Browser (software, desktop or mobile?) and version

Python client script for the REST API

### Operating system, dependency versions

MacOS

### Version

The currently running hosted Pretalx version.

**Comment by rixx** [comment]
Huh, yeah, that's a documentation bug, thank you for reporting it! Our review API has never delivered more user information than the ID since its introduction in dc63344fb.

**Comment by FlorianWilhelm** [comment]
Thanks @rixx, is there any other way to get the e-mail address of a reviewer? It would be really helpful as I need to join reviewers back to some internal system. The only option is to do that automatically via the e-mails.

**Comment by rixx** [comment]
I'd be open to accept a pull request to this extent, provided it makes sure the email is only shown to people with organisation management rights, *not* to reviewers (who also have access to the API).

Your current option to retrieve this information would be the CSV export, which has options for both reviewer name and reviewer email address.

**Comment by FlorianWilhelm** [comment]
Okay, I think it's better solved with a completely different endpoint that I described in this issue #1417.

**Comment by FlorianWilhelm** [comment]
One more thought on this. Using this endpoint right now there could be name collisions since two users could choose the same username. Thus with a larger number of reviewers the only option really is to use the CSV export. 
Does Pretalx internally use generated user_ids that one could use instead to link users? In this case it would be even more anonymous as right now.

**Comment by rixx** [comment]
Pretalx does have internal User IDs, but I'm not sure changing the API like that would be a good choice, as it's hardly backwards compatible.

**Comment by FlorianWilhelm** [comment]
I agree, this is a breaking change. One common way to handle this, is to have a versioning part in the API endpoint, e.g. `https://api.helpdesk.com/v1/...`. So when you break things you just start a new one like `https://api.helpdesk.com/v2/`. You could also use a schema like this to differentiate between the current stable API and some development API that has breaking changes.

**Comment by rixx** [comment]
I am aware of the concept of versioned APIs. I am, however, also aware of the maintenance burden.

I would be willing to discuss a versioned API if either a sponsor committed to commissioning the extra API version, or if an additional maintainer stepped up to maintain API versions, deprecations, documentation and so on. Otherwise, maintaining multiple API versions (if you suggest increasing from v1 to v2 for just this change, then imagine how soon we'd hit v28!) in addition to maintaining all of pretalx, adding new features and running pretalx.com – all as a side gig, mind you! – is not quite feasible, I'm afraid.

**Comment by FlorianWilhelm** [comment]
Yeah, I totally agree and sorry, I didn't mean to imply that you don't know what versioned APIs are. I only listed it for completeness for other readers.

The idea was more to have a stable v1 and a development v2 in which all breaking changes go until it is declared stable. So I don't think we would hit v28 soon as surely a lot of changes could go into v2 before declared stable. 

I really appreciate your work on Pretalx, it's a fantastic project and doing all this in your spare-time is a big contribution to the OSS community. Hopefully, a sponsor or some other contributor steps in to overhaul the current API in a new version as currently, it's just too limited. I would love to see Pretalx go API-first, so that I could do everything just by running my scripts.

**Comment by rixx** [comment]
All good, and sorry in turn for my tone – should've taken a day longer to respond.

I 100% agree that the API is too limited, but I honestly don't think API first will ever happen unless some magical sponsor appears; pretalx is too much of a frontend product for that. There's the hope to get at least the major endpoints writable this year – *if* this happens, I might make breaking changes to the API regardless, and those will definitely include several places where we will switch to IDs where we are currently using non-unique strings.

I'm not sure how to handle the transition yet – might be that we switch to versioned APIs (though I doubt it, and I honestly prefer the Stripe approach with its date-versioned headers), might be that we simply brek the API, regretfully.

(One trouble with that is that people hate retrieving details for all those IDs, so they'd prefer to get a `user` object rather than a `user` key, but that makes bulk serialisation terribly slow. I've been toying off and on with an `?expand` query param that would switch to embedded objects a layer or two deep …)

**Comment by FlorianWilhelm** [comment]
Hi @rixx, one more question came up, as I am writing down some best practices on how to use Pretalx for the PyConDE / PyData Berlin. Is it guaranteed that the user name returned by the review endpoint is unique? We currently use it to join it with our Google Sheet of external reviewers and having collisions here (many picked just their first name) might cause some trouble of course.
