### ISSUE TITLE
Allow submitters to submit to multiple tracks at once

### ISSUE THREAD

**Issue by daisylb** [pretalx/pretalx#1493]
### Problem and impact

For PyCon AU, we typically allow submitters to submit their proposals to multiple tracks at once. Actually making this happen in Pretalx as it stands currently has been a bit of a pain—because pretalx only supports a proposal being associated with a single track, we have had to implement tracks as a custom question, which is causing our reviewers pain when reviewing.

### Proposed solution / feature

Ideally, we'd like to be able to switch on a setting that turns the "Tracks" field in the submission form into a multiselect/list-of-checkboxes, and allow submitters to indicate that they're submitting their proposal for consideration in multiple tracks. We'd then assign it a track once it's selected.

**Comment by daisylb** [comment]
An alternate workflow that would work for us is if `/reviews/` could filter on answers to questions (similar to how `/submissions/` can (e.g. `/submissions/?&question=2507&answer__options=3136`). That would alleviate the problems our reviewers are facing with our existing workflow. I'm guessing that would be covered by #1183?

**Comment by rixx** [comment]
Questions filters now work on the reviews URL!

I'm not sure about the suggested feature – pretalx tries to stay somewhat neutral on what a "track" is, and implementing this would add quite a bit of complexity.¹  Nothing so complicated that it would make this feature impossible, just a lot to think about, and I'm undecided if the added maintenance burden is something I want to take on atm. I'll keep the issue open for now, as I absolutely see the use case!

---

¹ Just to expand on my reasoning so far: We'd either have to add full multi-track capabilities by transforming `track` to `tracks` and touching *all* code that ever interacts with tracks, or go with the way suggested in the issue here, and add a `submitted_tracks` field. But then, we either have to add yet another filterset (and the filter menu is crowded already), or interpret the "tracks" filter as handling both (but probably only both as long as no track has been selected?) and so on.

**Comment by rixx** [comment]
I've been thinking about this some more, and I think it's out of scope for pretalx. Tracks imply access permissions, which gets weird fast when tracks generally are 1:n, but here are m:n – for example, reviewers can be scoped to tracks, and so review teams would suddenly encounter one another when looking at a proposal to multiple tracks. Tracks also supply colour-coding etc, and as pretalx can't *make* organisers select one track at the end of the selection process, we'd have to deal with that, too.

I think the ideal workflow here would be to use a question, like you did, and then implement bulk changes, so that you could filter by something like "answer: Track X, track: null", select-all, deselect the talks you don't want to put into this track, apply the track, done.

(I know, closing this issue while the bulk changes haven't been built isn't great. … We'll at least have a writable API soon, so that may help build out parts of this as a script or a plugin until bulk changes #1330 get commissioned.)
