### ISSUE TITLE
Include session code inside schedule.json export

### ISSUE THREAD

**Issue by patrick91** [pretalx/pretalx#1501]
### Problem and impact

Hi there, I was working on EuroPython's website schedule and I needed to pull some more information about a session (information that's not available in the schedule, but is available in the submissions API).

Unfortunately, the code is not available in the API, so I had to resort to parsing the URL, which I don't think it is ideal.

### Proposed solution / feature

Add `code` to the session inside the schedule API/json export :)

**Comment by rixx** [comment]
I'm confused: the `code` attribute is available in the submissions API: 
![2023-06-12T01:04:02+02:00](https://github.com/pretalx/pretalx/assets/2657547/6ed830b4-a7c3-4200-a398-846a81cdbe0e)

Further comments for future refernece, and because you mentioned "the" JSON export (which we have multiple of):

- The `schedule.json` export is explicitly written to be compatible with [frab](/frab/frab), which doesn't have a `code` attribute and just uses numeric IDs, so that export will not be modified
   - notably, you could use custom exports instead
 - The `schedule/` API endpoint is currently not official – we only make any promises or development efforts for [documented](https://docs.pretalx.org/api/resources/index.html) endpoints
    - However, as far as I can tell, the `code` is included in the undocumented [schedule endpoint](https://pretalx.com/api/events/democon/schedules/v1.8/) as well
