### ISSUE TITLE
Profile picture constraint ignored

### ISSUE THREAD

**Issue by ligi** [pretalx/pretalx#1503]
### Problem and impact

I was setting Profile Picture to "ask and require input"

![image](https://github.com/pretalx/pretalx/assets/111600/6cd65123-98e2-4633-be65-543a4800bfc4)

Unfortunately people are still able to submit an application without the profile picture.
I changed this constraint while the cfp was already opened - can this be a factor for the bug?

### Expected behaviour

Should enforce that submissions submit a Profile Picture

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
Anything submitted before you made the change would not include a profile picture, of course (though if they want to update their profile at any point, they'll have to submit one). Other than that, the only other thing is that pretalx permits people to use their gravatar instead of a profile image, maybe that's part of the confusion?

I just opened the /democon cfp for a bit with the avatar set to be required, and didn't mention to submit a proposal without a profile picture. As far as I know, we also have tests for this, so I'll tentatively close and re-open on reproduction.

**Comment by ligi** [comment]
hm - weird. There was no gravatar and I tested after making the change
