### ISSUE TITLE
Session Confirmation Text

### ISSUE THREAD

**Issue by clytaemnestra** [pretalx/pretalx#1520]
### Problem and impact

Hi, we encountered an issue that when users click on the link to accept the proposal, it redirects them to the page where at the end of it there's the following text: 

> [...] The proposal data, such as title, abstract, description, and any uploads you provided, can be made publicly available once the proposal is confirmed.  

This is a bit problematic for us, as our flow is the opposite:
1. first we ask users to confirm their sessions ASAP, as we need to deal with the users on the waiting list and we don't want to make them wait for too long, especially those coming from 3rd world countries that need visa to enter the Czech Republic,
2. then we ask them to upload photos and adjust their description, if needed -> this action usually takes them quite a lot of time and they tend to do it in the last minute, therefore we don't include this right at the beginning.

I checked the source code and I noticed that this text is hard-coded inside the template. I'd like to ask just in case if there's any custom option to disable this text? 

Thanks,
Mia  

Screenshot:
![image](https://github.com/pretalx/pretalx/assets/38294198/e54eddce-36fc-4283-b683-1ff5ebc5deb2)

**Comment by rixx** [comment]
Sorry, but offering a custom text there is out of scope for now, I think, both due to settings fatigue (pretalx already has a ton of settings, including custom texts), and because I do think that the text is warranted. It does not state that the contents **will** become public immediately, just that they **can** be made public – this is in the spirit of the GDPR, which asks us to make it clear to users which of their data is going to be used in which way.

(We are not strictly required to put this information there, as we already warn users about publishable fields when they submit their data, but that's often weeks or months earlier, and I'd consider it in the spirit of data protection and transparency to make sure that users are informed about what can happen).

As a conference organiser, I'd probably put this information in the acceptance email and/or further emails when reminding people to fill in their data and/or to click the confirmation link.

(Sorry that this sounds negative, it's just really tempting to add settings for basically *all* the texts, and that would render the pretalx settings pages pretty much unusable.)
