### ISSUE TITLE
Search functionality: recognize names without correct accents

### ISSUE THREAD

**Issue by clytaemnestra** [pretalx/pretalx#1555]
### Problem and impact

When I try to search for a speaker using a name without non-English characters, I don't get any results. For instance, if I input "Lumir", nothing comes up, but when I use the Czech accent as in "Lumír", it works. It would be great if the search function could recognize names even without the correct accents. 🙂 

### Context or examples

![image](https://github.com/pretalx/pretalx/assets/38294198/ffae9fa6-358e-401c-a1ea-26c2f7f80099)
![image](https://github.com/pretalx/pretalx/assets/38294198/a65ff420-5821-4afd-a982-0befc19aa790)

**Comment by rixx** [comment]
Accent-insensitive search isn't trivial, I'm afraid. I'd love to have it in pretalx, but since pretalx currently supports multiple databases, and each database uses its own collation features, anybody implementing this will have to:

- Document the [proper mariadb configuration](https://stackoverflow.com/questions/65593014/is-there-a-way-to-perform-accent-insensitive-lookups-using-django-and-mariadb), which then should immediately work with our `__icontains` filter
- For postgres, we'd need to use the [unaccent](https://docs.djangoproject.com/en/dev/ref/contrib/postgres/lookups/#std:fieldlookup-unaccent) lookup, which also requires `django.contrib.postgres` in our `INSTALLED_APPS`, so we'd need two further places where code needs to do different things based on the database in use: the `settings.py` and then the search, which will need to use `__unaccent__icontains` when postgres is in use, and `__icontains` otherwise
- For SQLite, … we'd probably need to create the collation, similar to what Adam does [here](https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/) (only with sqlite and its [create collation](https://stackoverflow.com/questions/14009261/sqlite-accent-insensitive-search), and then also use that collation.

Frankly, I'm not sure it's worth the maintenance effort at this point. I'd also prefer to have accent insensitive search, but maintaining two janky solutions, plus docs support for the less janky one (on the Django side, at least) sounds like a huge hassle. If anybody wants to step in and contribute, including tests, I'd be willing to talk about it, but until then, I'll close this as "not planned" (pending better Django support or outside contributions).
