### ISSUE TITLE
Public link not public

### ISSUE THREAD

**Issue by ligi** [pretalx/pretalx#1613]
When a talk transitions to "confirmed" - then organizers get the option "public link" - but initially this works when you are logged in as organizer - but 404s when you are not. Guess this is because the talk is yet unscheduled?! UX wise this is a bit weird and can lead to high WTF/minute. Also it would be nice to be able to use this before scheduling to announce a talk e.g. on socials before having a concrete time.

**Comment by rixx** [comment]
I wouldn't class this as a bug. (Also, if you're getting a high WTF/minute from this, maybe clicking the link less often per minute would also work …)

We can rename the link to "frontend URL", I suppose. Having only scheduled talks available publicly is, so far, a feature, not a bug. Changing this behaviour would also mean, among other things, changing API behaviour, feedback and reviewer permissions (as feedback relies on the session having taken place), etc.

There's the "highlighted sessions" page for the purpose of pre-announcing sessions (regardless of confirmation status!).

**Comment by ligi** [comment]
Thanks for the swift reply. To me it felt like a bug as I clicked on "public link" and the link was not public. 

> There's the "highlighted sessions" page for the purpose of pre-announcing sessions (regardless of confirmation status!).

that sounds great - but when searching for it I found nothing. Do you have some link? I checked "featured" at one session but still the link is not public

**Comment by ligi** [comment]
I think I found out what you mean with highlighted sessions - I clicked "featured" and now can see them in the schedule preview - but the link is still 404ing. So it does not really seem to help with getting a link for unscheduled talk.

**Comment by rixx** [comment]
Looked into this some more – you're right that this isn't great, especially as (as a related bug), sessions on the featured page never had detail pages. In all fairness, that's because currently the `/featured/` page does not link to individual talk pages – because *those* in turn link to speakers, so we'd need to make sure those links aren't dead either. Also they contain scheduling data, and we'd have to hide the scheduling data if the featured page is public, but the schedule (albeit released!) isn't. Lots to think about.

What I did for now:

- If the proposal is visible to not-logged in users, show the "public link" link in the dropdown. This *includes* featured talks, which now will be accessible on their own talk page. They aren't linked from the featured talk list page yet, though, since I need to double-check all content on the talk page for this. Tracking at #1662 
- If the proposal is not visible to not-logged in users, **but** is either accepted or confirmed, show the link as "Public link (not public yet)" – I hope that's somewhat understandable, and should make it still easy for organisers to e.g. plan out their social media links or whatever else accessing the link in advance would be useful for

![2024-01-29T11:18:35+01:00](https://github.com/pretalx/pretalx/assets/2657547/fef41a9c-2917-48cd-81f2-2393e4e82f15)

Hope this makes sense!
