### ISSUE TITLE
"Hold pattern" an other email options

### ISSUE THREAD

**Issue by RichiH** [pretalx/pretalx#1641]
### Problem and impact

When accepting and rejecting speakers, I personally always keep a few of the highest-rated talks which did not get accepted in review in case other speakers do not re-confirm their attendance.

This leads to problem as there is usually already public communication by speakers about being accepted/rejected and then on-hold speakers start reaching out to see what their status is.

### Proposed solution / feature

It would be good to be able to send them a "you are currently on the short list" kind of email. Or have a generic email template.

### Context or examples

https://github.com/pretalx/pretalx/issues/1330 is related inasmuch as this would be a bulk action.

**Comment by rixx** [comment]
I don't think we need a generic email template for that – you could send an email to those specific proposals with the normal email editor (by selecting either the specific proposals, or simply all proposals you've left as "submitted" rather than "accepted").

You could even set the proposals to "submitted, pending accepted" to make it clear to other organisers what's going on, and to make it easier to accept them at a later date.
