### ISSUE TITLE
Total Proposals number in Statistics don't add up.

### ISSUE THREAD

**Issue by FlorianWilhelm** [pretalx/pretalx#1649]
### Problem and impact

Looking at the screenshots below from the Proposals -> Statistics, the total number of proposals don't add up. The first graphic shows a total number of 315, but this is less than the number reported elsewhere like below if you add 265+63+57= 385.

### Expected behaviour

The number in the statistics of submitted proposals over time should reflect the total number of proposals.

### Steps to reproduce

1. Have same proposals
2. Check the Statics menue.

### Screenshots

![image](https://github.com/pretalx/pretalx/assets/3184072/f4777d47-3486-4c56-990c-936f89b20ad3)

### Link

https://pretalx.com/orga/event/pyconde-pydata-2024/submissions/statistics/

### Browser (software, desktop or mobile?) and version

Chrome

### Operating system, dependency versions

MacOS

### Version

Hosted Version

**Comment by rixx** [comment]
Some proposals seem to come without a creation log entry. That's … not great. We can't really fall back on creation timestamps, as those would record proposal creation rather than submission. I don't think there's a way to fix this for existing events, though we may be able to fix it for future events, depending on the reason the log entry is missing.

**Comment by rixx** [comment]
Fixed the data as much as possible. There's still a remaining mismatch, and I'm not sure where that comes from, but it's much less extreme.

**Comment by FlorianWilhelm** [comment]
Thanks for fixing this so fast and cool that it will work for future events.
