### ISSUE TITLE
Behaviour of media path changes between v2.3.2 and v2023.1.3

### ISSUE THREAD

**Issue by GitHubSwimmer** [pretalx/pretalx#1651]
### Problem and impact

After an update from v2.3.2 to v2023.1.3 the pretalx "engine" does not show pictures from the media folder anymore, if debug = False.  Ok, i can fix this with nginx and maybe this is an wanted behavior. 
But if debug = True, the behavior is like before the release update and all media content is available without  modifying my nginx configuration.

**Comment by rixx** [comment]
Yes, in development mode, pretalx will serve the `/media` directory itself. Otherwise, it won't – this is documented in the [sample nginx file](https://docs.pretalx.org/administrator/installation.html#step-7-ssl) in the setup docs for administrators.

If pretalx has ever served media files in production mode, that was both undocumented and unintended. I don't believe we have made any changes to affect media file handling. Please use your web server of choice to serve media files.
