### ISSUE TITLE
Incorrect character count for abstract during proposal submission

### ISSUE THREAD

**Issue by sloede** [pretalx/pretalx#1660]
### Problem and impact

When trying to submit an abstract, I received an error that my abstract submission is too long (502 characters) and that the maximum allowed number of characters is 500. However, VS Code, `wc`, and several online character counting websites confirm that the character count is 497 and that it is indeed also just 497 bytes (I'm using ASCII only).

Interestingly, the live validator (JavaScript?) allows me to add three more characters before refusing to add more, apparently correctly counting the original 497 characters. It thus seems to me like only the backend validation on the server is somehow broken.

This occurred during a [submission to JuliaCon 2024](https://pretalx.com/juliacon2024/submit/).

cc @oxinabox

### Steps to reproduce

1.
2.
3.
4.

### Link

https://pretalx.com/juliacon2024/submit/

### Browser (software, desktop or mobile?) and version

Firefox 121.0.1

### Operating system, dependency versions

macOS

**Comment by rixx** [comment]
Huh, thanks for reporting this. We're counting words in the backend as `length = len(re.findall(r"\b\w+\b", value))` (https://github.com/pretalx/pretalx/blob/main/src/pretalx/common/forms/utils.py#L38), so any set of characters in between spaces. I thought this would be fairly lenient – happy to take suggestions for improvements. Alternatively, feel free to send me your original text to `r@rixx.de` and I can figure something out.

**Comment by JoshuaLampert** [comment]
As far as I can tell `length = len(value)` (https://github.com/pretalx/pretalx/blob/main/src/pretalx/common/forms/utils.py#L36) is relevant because it is about character count rather than word count. Maybe the line breaks (you have 5 line breaks and the difference is 502-497=5) are the problem?

**Comment by rixx** [comment]
Oh sorry, I somehow thought you were talking about word counts, which I thought way more likely to be wonky.

Yes, line breaks are included in character counts, but that's not unusual at all – in my experience, all kinds of character-counting web tools (like the Twitter/Mastodon boxes) count line breaks in their character counts. Otherwise you could just replace tons of spaces (which count) with newlines and have them not count.

However, I don't think line breaks are the problem. When running the unwrapped text above through `wc`

> echo "Homomorphic encryption allows one to perform computations on encrypted data and obtain the same result as with the original, unencrypted data. This makes it possible to securely process sensitive data in untrusted compute environments. In this talk, we will demonstrate how to easily set up and execute homomorphically encrypted computations in Julia and show which kind of operations are possible. We will present examples for secure algorithms and discuss challenges and limitations in practice." | wc -c

I get `498`, so pretalx should also accept this input. And indeed, `len("Homomorphic encryption allows one to perform computations on encrypted data and obtain the same result as with the original, unencrypted data. This makes it possible to securely process sensitive data in untrusted compute environments. In this talk, we will demonstrate how to easily set up and execute homomorphically encrypted computations in Julia and show which kind of operations are possible. We will present examples for secure algorithms and discuss challenges and limitations in practice.")` is also `497`.

It seems however like pretalx is overcounting line breaks, as it counts them as two characters (`\r\n`) rather than one  – so there's the bug. To everybody running into this before your instance receives the fix (which will be released in `v2024.01` or immediately on pretalx.com): Reducing your amount of line breaks works for now, in a pinch.

**Comment by sloede** [comment]
Thanks for looking into and fixing this so quickly 👍
