### ISSUE TITLE
Review page is very slow with a lot of proposals

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1675]
### Problem and impact

At FOSDEM, we had 1894 proposals. 
Showing all reviews when clicking the review link is not very useful (we limited it to 200 for performance reasons), but you have to open the full page anyway even if you are only interested in a specific track.

### Proposed solution / feature

Some options:
* 'remember' the last track that was selected and show only that track. 
* don't show reviews without pressing 'search'
* limit the number of reviews to make sure the page loads even if nothing is selected.

I'm in favor of the first solution, but before jumping into coding I'd like to hear what others think.

**Comment by MasinAD** [comment]
Out of curiosity, as we also stumbled upon this massive slowness with only 81 reviews taking 16 seconds to display: What is happening there? Why is it so slow?

**Comment by rixx** [comment]
The exact cause will depend on your event and your review process configuration. If you want to see details, setting up a dev environment replicating your event settings and using django-debug-toolbar to trace queries is probably the best way to go.

**Comment by MasinAD** [comment]
It turned out that Pretalx issued more than 2400 SQL commands to retrieve the review list. As the SQL server was at a different location with 8ms latency that added up to several seconds. We moved the DB closer to pretalx with now just 0.07ms latency. Loading the list is now at 1.6 seconds.

I am no expert in SQL, database design or database development but 2400 requests seems a little bit excessive. The FOSDEM case with about 1900 reviews is about 24 times as much as ours and would take more than half a minute to load with our current setup or 5 minutes with the earlier one.

Maybe someone with greater knowledge of pretalx' internals and SQL could take a look at this. There seems to be some unused potential to lift. If the DB queries were a little bit more optimized pagination wouldn't be necessary.

**Comment by rixx** [comment]
- Yes, 2.4k requests is excessive, and this should definitely be improved upon. Pull Requests are very welcome.
- Comparing across events makes very little sense however, as the actual review setup (review phases, review score categories, review teams, independent scores vs calculated scores) will all impact the final query count.
