### ISSUE TITLE
Exported schedule fails to render

### ISSUE THREAD

**Issue by bengerman13** [pretalx/pretalx#1698]
Apologies if I'm way off-base in where this issue belongs.

I'm trying to get an exported schedule for my event working. To test, I followed these steps:
1. created the export today
1. unzipped the download
1. served the content locally from the root of the extracted folder
1. opened the page in my browser (`localhost:8080/my-event-2024/schedule/`)

The grid spins forever, and devtools shows 404s for `/my-event-2024/schedule/v/1.2/widget.json` and `/my-event-2024/schedule/v/1.2/widget/v2.json`

grepping through some files, I *think* this is supposed to point to `/my-event-2024/schedule/v/1.2/widget/schedule.json`. I tried manually updating `/my-event-2024/widgets/schedule.js`, and it seems to have fixed the load issue for me, but I assume there are more compatibility concerns here. 

I _think_ the code [here](https://github.com/pretalx/schedule/blob/41ec1c6750cbaf8fce81b3518df01f1c9039632e/src/App.vue#L181-L182) needs to have `widget/schedule.json` added as another possible source, but I'm far from sure about that.

LMK if you need any more information - happy to help however I can

**Comment by rixx** [comment]
Heh – I actually was wrong to transfer this – I had assumed that our url gathering was once again broken, but it turns out that we have a typo in our JS schedule – it's supposed to be `widgets/schedule.json`, not `widget/schedule.json`, as the source currently says. The fact that `widget.json` is present at all is completely incorrect, too – probably not enough to require a bugfix release, but definitely something to be fixed here in the main repo.
