### ISSUE TITLE
Email Placeholder Feature: Event Dates

### ISSUE THREAD

**Issue by bushong1** [pretalx/pretalx#1701]
### Problem and impact

When I'm sending out emails to accept speakers, I want to include the dates of the event so that we can easily communicate to submitters when the event is.

### Proposed solution / feature

An email placeholder for {event_dates} would make it easier to retain templates from event to event.

### Context or examples

```
We have accepted your proposal for {event_name}!  Please confirm your ability to attend on {event_dates} by clicking the link below.
```

**Comment by rixx** [comment]
I'm of two minds here – on the one hand, this placeholder would be trivial to add. On the other hand, I'm already being told that users find the placeholders sidebar overwhelming and confusing, so we should maybe hold off on adding other placeholders … Really not sure in which direction to take this.

**Comment by rixx** [comment]
Another thought: event dates need localised formatting, and organisers would want to anticipate the format – does it include all event dates? How are they formatted? How will they be formatted in a language where we do not yet have a custom timerange formatter? etc.

I think in this case, asking speakers to confirm their attendance is likely better done by asking them to confirm their specific date(s) rather than the whole event.

Closing this because it's out of scope for now, but if anybody wants to implement this, given the considerations above, I'd be happy to review the PR!
