### ISSUE TITLE
Quoting change impacts exports, exports view headers present incorrect charset

### ISSUE THREAD

**Issue by zollman** [pretalx/pretalx#1711]
### Problem and impact

CSV exports now have unicode headings `Score in “...”` instead of `Score in '...'`.

The exporter does not explicitly set an encoding of UTF-8, so automation built atop the CSV exports fails & includes Unicode decoding errors.

(as background: fwdcloudsec.org, now in our 3rd year using pretalx, has built automation which pulls a CSV export of reviews and submissions every morning, that drives a custom scoring workflow for our review panels built atop google sheets. I will gladly open source this someday. It's not critical but we find it makes synthesizing reviews across over 100 submissions considerably easier. In the meantime, I have built a workaround into my scripts so this is a low priority request.)

### Expected behaviour

Either:
1. Revert the *specific quoting change* to `Score in...`, lines 327/334 in `src/pretalx/orga/forms/review.py`, OR
2. Change the encoding to explicitly be utf-8 - I have not tested this but believe it's a change to `src/pretalx/orga/forms/export.py` line 165 to change the encoding to `text/csv; charset=utf-8`

My preference would be 1, but I'm OK being in the minority here as I can imagine others would like unicode characters in their field names.

### Steps to reproduce

Run through an export, eg `https://pretalx.com/orga/event/your-event-name/reviews/export/` - look at the headers in developer tools; there is no `Content-Encoding` and `Content-Type` is `text/plain`.

I have horrible requests code that will parse for a CSRF token and then include it in a `POST` to the export page - happy to add that to this ticket if helpful.

**Comment by zollman** [comment]
This is a result of the changes in https://github.com/pretalx/pretalx/commit/3445853591979c2398a4125e7824a2633bb05da1 .

Given @rixx 's guidance on preference between option #1 and #2, I can probably get a dev environment set up and a PR put together in a few days - let me know if that would be helpful.

**Comment by rixx** [comment]
Yeah, I can see how that would be annoying, thank you for writing this issue.

Looked at the code some more, and I don't honestly know why we use the "Score in" translated string, when we might just as well put just the category name in there – all this does is that it makes people parse out the "Score in" on the other end.

However, as score categories can contain unicode, we'll need to make sure that the CSV export is properly encoded, so this will be a two-part fix.

**Comment by rixx** [comment]
Two more notes:

1. Upon further testing: It's true that no content encoding is specified – which leaves matters up to your system. When I download the file, my system interprets it as `CSV Unicode text, UTF-8 text` – I agree that we should make this explicit, for everybody who is inexplicably not assuming to read unicode, but I do consider it a rather niche behaviour.
2. I don't believe we should send a Content-Encoding header, as this is a file response. I'll add a `; charset=utf-8` to the Content-Type header, so for the CSV export: `Content-Type: text/plain; charset=utf-8`

I assume you aren't using the API because you need the individual scores to be included? I hope that this will be the case in the new API that will come later this year, fwiw. Having people parse the website for CSRF tokens is definitely not the intended way of getting data out of pretalx!
