### ISSUE TITLE
404 media folder (css,

### ISSUE THREAD

**Issue by turbotimon** [pretalx/pretalx#1720]
### Problem and impact

Beeing aware, that there are several other issues covering this (#1655 #903), this took me hours to find out and it still does not work the way I want it. Therefore I have some question and may would like to suggest improve user experience.

1. What's the reasion pretalx won't serve `media` and `static` when debug is off? And could that be an option?

2. In my case (and without serving any of this folders, debug=false), pretalx will serve `static` but not `media`. Is this intended? Or is this a bug or is the [documentation](https://docs.pretalx.org/administrator/installation/#step-7-ssl) wrong?

Example:
```
https://pretalx.***.ch/media/myevent/cfp...css    404 Not Found
https://pretalx.***.ch/static/vendored/...    200 OK
```

3. When I try to configure pretalx to use an other path, pretalx is still placing `static` under `data/`:
```
[filesystem]
# use PRETALX_FILESYSTEM_* env vars
data = /data
media = /public/media
static = /public/static
logs = /data/logs
```

```
$ ls /data/static
CACHE              bs-62ab5f6f.js     en-nz-d5b60096.js  gd-fcd3dad9.js
...
```

```
$ ls /public
media
# but not static
```

4. In general, would you be open for a PR to mention that more prominently on the [installation](https://docs.pretalx.org/administrator/installation) page?

### Version

v2024.1.0

**Comment by rixx** [comment]
1. pretalx won't serve media files because Django, the framework we use, recommends to leave media file serving to a proper webserver.
2. static files are served via pretalx as a fallback, though we still recommend using the primary webserver to serve these files for performance reasons.
3. Did you remove the old staticfiles directory, and did you run `rebuild` again? When I set `[filesystem]static = /tmp/static` and re-run `rebuild`, I end up with files in `/tmp/static`.
4. Not sure where we should document that we're happy for contributions, apart from our [existing docs](https://docs.pretalx.org/developer/contributing/).

**Comment by rixx** [comment]
> Is this behavior documented? It has confused me a lot..

It is not, as it is entirely incidental, and the recommendation of forwarding `/static/` through the SSL-terminating webserver stands. If this behaviour is too confusing, I'll gladly merge a PR disabling the `/static/` forwarding via a setting in the production mode.

> If I remember correctly, i did a rebuild, but i will try again!

A reproducible bug of pretalx *not* using the configured staticfiles directory is of course a bug that needs to be fixed. In order to make that happen, please provide a reproducible scenario in which pretalx does not use the configured staticfiles directory!

> My recommendation would be to add a note/warning in the following places:

The documentation currently says:

![2024-03-26T18:16:05+01:00](https://github.com/pretalx/pretalx/assets/2657547/2e6a5adc-3e84-4b4a-92de-711753c10ae3)

I don't believe a `.. note` or `.. warning` is necessary here – it'd also be an arbitrary of one fact of that list, and not the most important one.

After this bullet-point list, there is also an nginx configuration showing how to achieve this. I had imagined that nginx was enough of a currently-standard tool that users deciding to use other webservers would work through the example configuration in order to see what they'd need to do with their webserver of choice. As it feels like having the configuration snippet available draws the reader's eyes away from the important parts of the documentation, I'll remove it to make sure the important part of the documentation is highlighted.

I've also renamed that subheading to "Reverse proxy".

> What do you think? I can make then a PR

done via 8f66ae62c

**Comment by turbotimon** [comment]
Personally, I still think it would be helpful to point this out since it's not obvious and [other people have said so](https://github.com/pretalx/pretalx/issues/903#issuecomment-605246976). I also don't think removing the ngnix example makes it any better (rather the other way around). But in the end, of course, it's your decision.

**Comment by rixx** [comment]
Like I said: I believe repeating *one* of the five important tasks of the forwarding webserver in a separate pop-up will make people ignore that part. As forwarding the static and media files isn't the most important part / the only important part, I don't think highlighting only that is a good idea, even if a handful of people over the years won't notice it immediately.

I *do* think that people keep missing these points due to the temptation of just copying an nginx file, as they seem to have been reading the documentation in general. Since providing an nginx snippet is unnecessarily opinionated, requires maintenance, and also seems to draw people away from the important point (as you yourself pointed out you searched for the problem, including in the docs, for hours – which of course isn't intended!), removing it makes sense to me. This, together with the renamed heading, should hopefully help people in the future.
