### ISSUE TITLE
Markdown headers get bigger at header level 4

### ISSUE THREAD

**Issue by jidanni** [pretalx/pretalx#1749]
### Problem and impact

Using this file,
```
# 1
## 2
### 3
#### 4
##### 5
###### 6
```
the rendered headers should get smaller.
But at 4, they suddenly get bigger. Let's see how GitHub renders them,

# 1
###### 6

Looks fine.

Alas, not here:
![Screenshot 2024-04-20 15 02 12](https://github.com/pretalx/pretalx/assets/1230959/84abec9b-23d5-48ae-b8af-d9458cfe3ce6)

**Comment by rixx** [comment]
As far as I can tell, this bug is only a problem within the preview, and does not show up when rendering the actual pages.

**Comment by rixx** [comment]
Actually, I cannot reproduce this bug at all in the Markdown preview, whereas in the rendered content,`h4` and `h5` tags seem to show up as the same font size (which is not ideal, of course).

Please include **all** the relevant information requested in the bug template. Things like browser versions and instance of pretalx in use can make a difference to looking at (and reproducing/fixing) these bugs. We put these fields there for a reason, and may close bug reports that do not fill them in.

In this instance, the bug was not reproducible in dev/production, and knowing if you only tested the preview, and if you're referring to the preview in the speaker view or the organiser view would have helped make this process shorter.

**Comment by jidanni** [comment]
I saw it on both
https://pretalx.com/sotm2024/talk/review
https://pretalx.com/sotm2024/me/submissions
in chrome on a chromebook. But I'm glad it is
not as bad in your newer versions as you say,
so no reason to reopen this bug.
