### ISSUE TITLE
Markdown only partially rendered in Session list entry

### ISSUE THREAD

**Issue by paulmelis** [pretalx/pretalx#1790]
### Problem and impact

We have a session titled "Posters" whose abstract contains this piece of markdown:

```
# Posters

**Debate and Discover Public Values with XR Cards**
...
```

When switching to Session mode the Posters header from the abstract shows as raw markdown, while the bold text below it is shown correctly:

![image](https://github.com/pretalx/pretalx/assets/1408287/65a978a9-3f1b-478f-8b72-dab35749e1c2)

When viewing the session's details the rendering is correct:

![image](https://github.com/pretalx/pretalx/assets/1408287/f81faa77-3d91-48b6-a7b7-84297e9526bb)

Perhaps this is related to #1574, but I'm not actually sure?

PS I'm going to remove the `# Posters` header anyway from the abstract, as the title is enough, but still wanted to report the bug.

### Expected behaviour

No raw markdown visible, but rendered correctly

### Steps to reproduce

1.
2.
3.
4.

### Link

https://pretalx.surf.nl/national-xr-day-2024/talk/

### Browser (software, desktop or mobile?) and version

Firefox 127.0, Chromium 126.0.6478.55

### Version

2024.1.0

**Comment by rixx** [comment]
I'm afraid this behaviour is semi-intentional (though it is true that this is *yet another* markdown renderer involved). The reason that we don't render headlines here is that there's simply no way to win – imagine if we were to include a fat `<h1>` headline in the middle of the list of sessions here!

For this reason, and because abstracts only very rarely contain a headline (the longer description blocks do, sometimes), the short preview of session contents are rendered with the `renderInline` functionality, which is exactly designed to keep things in a text flow rather than paragraph-level flow.

If anybody wants to go to the effort and design some CSS that will permit arbitrary Markdown rendering *without* breaking the design, I'd be willing to review and merge that; but I'm afraid I won't be able to prioritise this myself.
