### ISSUE TITLE
Schedule Editor: Collapse expanded time slots

### ISSUE THREAD

**Issue by turbotimon** [pretalx/pretalx#1817]
### Problem and impact

How can once expanded hours be collapsed again, so the tiny dots are not visible in the view?
![image](https://github.com/user-attachments/assets/0b243bbd-fd1a-4f4a-9836-c2b1496e8a79)

Thanks in advance

### Version

2024.1.0

**Comment by turbotimon** [comment]
(btw, i hat this issue too https://github.com/pretalx/pretalx/issues/1702 but just found out that it's fixed so i removed it from the issue)

**Comment by turbotimon** [comment]
somewhat relate to #1606

**Comment by rixx** [comment]
incomplete informa

**Comment by turbotimon** [comment]
Dear Tobias, could you give me a hint as to what information you need or what part of the question is unclear? Since the problem is not related to an operating system, I didn't provided that part. I have tried to be as brief as possible, but we are of course happy to provide more information. Also, I tried to find something about this feature in the docs, FAQ or old issues, but couldn't find anything. Thanks in advance

**Comment by rixx** [comment]
Dear Timon, you have posted a bug report, but not filled in any of the provided fields. A bug report is only complete when you include:

- the problem and impact
- the expected behaviour
- the steps to reproduce the bug

What you wrote instead,

> How can once expanded hours be collapsed again, so the tiny dots are not visible in the view?

is at best a support request, which should be over at [Discussions](/pretalx/pretalx/discussions/). This is also indicated when you [create a new issue](https://github.com/pretalx/pretalx/issues/new/choose). We choose to do this because all bugs are treated as potential blockers for a new release, and support requests are not. However, even as a support request, it's not clear what you did, what you hoped to do, and what "the view" refers to.

Now, I could try to guess what the problem is, but that's a) liable to wrong, and b) shifting the effort required to the maintainer rather than the reporting user. As there are many users and only one maintainer, that's obviously a bad idea and won't scale. I'll demonstrate this once, so there's a clear indication of the work involved in this, and so I can point at this issue when I close similar sparse issues in the future. So, as an exercise, if I *had* to guess what you were trying to say, it would be this:

Your first screenshot shows the schedule editor (information also worth including, btw). You clicked to expand a time slot in the schedule editor. You'd like to unexpand it again. There is no UI for that at the moment, and I doubt there will be any time soon, because guessing the time frame to be unexpanded is hard. Instead, you can reload the window, as expanded time slots are not persisted. Your second screenshot shows the public schedule, not the schedule editor (information **very** worth including, as the two look nearly the same and it requires a fairly in-depth knowledge of pretalx to spot the difference. I didn't at first, fwiw, so I wasted time on Saturday trying to reproduce something completely different). In the public schedule, there are dots on the timeline to indicate that the block displayed is longer than the default 30 minutes. This is done because often, most blocks indicate a 30 minute duration, and when a longer block isn't visually indicated, people will miss that it takes up more time, and will fail to schedule accordingly. These dots are not configurable and can't be hidden directly, though you could try to add custom CSS if you don't like them. The dots have no connection with a once-expanded time slot in the schedule editor, as those are not persisted.

**Comment by turbotimon** [comment]
Dear Tobias. Thank you a lot for your detailed answer and apologize for the problems caused. I can see what was the problem and also what was not clear. (I wanted to write "in the public view", but apparently the “public” didn't made it from my head to the keyboard..) I will use Disuccsion in the future for such questions.
