### ISSUE TITLE
Images with umlauts in their file name are not contained in the exported ZIP

### ISSUE THREAD

**Issue by almereyda** [pretalx/pretalx#1828]
When exporting an event to which people have submit images that contain umlauts in their file name, they are not included in the export. Instead, 404 HTML pages are served for their paths.

As encountered on:

- https://agrikulturfestival.berlin.allmende.io/schedule/
- https://agrikulturfestival.berlin.allmende.io/talk/FWQDSC/
- https://agrikulturfestival.berlin.allmende.io/talk/AXN7EL/
- https://agrikulturfestival.berlin.allmende.io/talk/WDHVAF/
- https://agrikulturfestival.berlin.allmende.io/talk/DUQYJB/

Also their file names will be URL-encoded in the file system already, which eventually defies serving the file by a web server.

- https://agrikulturfestival.berlin.allmende.io/media/avatars/220427_Tiny_Farms_Portr%C3%A4ts_Carla_Ulrich-9_GxHNIan.jpg
- https://agrikulturfestival.berlin.allmende.io/media/avatars/sch%C3%BChle-florian_UdJcVTm.jpg
- https://agrikulturfestival.berlin.allmende.io/media/avatars/RESTLOS_GL%C3%9CCKLICH_Logo_Pink_2_3lG8NTa.png

The 404 error message contained in the files with URL-encoded file names are not served:

- https://lab.allmende.io/agrikulturfestival/schedule.berlin.2024/-/blob/main/public/media/avatars/220427_Tiny_Farms_Portr%25C3%25A4ts_Carla_Ulrich-9_GxHNIan.jpg
- https://lab.allmende.io/agrikulturfestival/schedule.berlin.2024/-/blob/main/public/media/avatars/RESTLOS_GL%25C3%259CCKLICH_Logo_Pink_2_3lG8NTa.png
- https://lab.allmende.io/agrikulturfestival/schedule.berlin.2024/-/blob/main/public/media/avatars/sch%25C3%25BChle-florian_UdJcVTm.jpg

The live counterparts from the Pretalx instance do not show the regression:

- https://pretalx.allmende.io/agrikulturfestival-berlin-2024/schedule/
- https://pretalx.allmende.io/agrikulturfestival-berlin-2024/talk/FWQDSC/
- https://pretalx.allmende.io/agrikulturfestival-berlin-2024/talk/AXN7EL/
- https://pretalx.allmende.io/agrikulturfestival-berlin-2024/talk/WDHVAF/
- https://pretalx.allmende.io/agrikulturfestival-berlin-2024/talk/DUQYJB/
- https://pretalx.allmende.io/media/avatars/220427_Tiny_Farms_Portr%C3%A4ts_Carla_Ulrich-9_GxHNIan.jpg
- https://pretalx.allmende.io/media/avatars/sch%C3%BChle-florian_UdJcVTm.jpg
- https://pretalx.allmende.io/media/avatars/RESTLOS_GL%C3%9CCKLICH_Logo_Pink_2_3lG8NTa.png

@rixx Are you still able to reproduce this in pretalx/schedule#24? If not, we may already have a fix.

Please note that this is a customised schedule, which was modified to remove the relative path of the event, because the site is already served from a subdomain related to it.

- https://lab.allmende.io/agrikulturfestival/schedule.berlin.2024/-/blob/main/README.md

**Comment by almereyda** [comment]
Thank you for the explanation and the quick fix.

**Comment by rixx** [comment]
Fixed now.

**Comment by rixx** [comment]
> I'm not able to confirm this

Sorry to hear that, but in my local tests, a file called `lüstíg_4uY7D2U.jpg` is exported to the `/media/democon/submissions/ZXHLFB/` directory, and another file called `lüstíg_CJUTgJB.jpg` is exported to the `/media/democon/submissions/ZXHLFB/resources` directory, which is as intended, I should think, as it mirrors the local, non-HTML-export media directory, and leaves the HTML decoding up to the web server.

Sorry I don't have the time rn to go through 12 pages of git diffs to see where your export differs. I saw 404 html pages generated before I committed the fix, and supplied both automatic and manual tests to make sure the problem is solved this time. No idea why your export won't work correctly.

Actually, I sighed and *did* go through the diff to see what's all wrong. One example, [this file](https://lab.allmende.io/agrikulturfestival/schedule.berlin.2024/-/blob/8fb768f6877b7e4e81be27d4349d53d4f029c48d/public/media/agrikulturfestival-berlin-2024/submissions/M38XC3/Ideen_f%25C3%25BCr_Wriezener_Park_9lwoHfv.jpeg) has a title that decodes clearly with the code we are using:

```python
>>> import urllib.parse
>>> urllib.parse.unquote("Ideen_f%C3%BCr_Wriezener_Park_9lwoHfv.jpeg")
'Ideen_für_Wriezener_Park_9lwoHfv.jpeg'
```

So I'm fairly confident that our code is doing alright. If you want to add local print debugging (or step through with the debugger), you could trigger it on the url string including "Wriezener" and go from there.
