### ISSUE TITLE
Clicking "Skip for now" on last review results in minor error

### ISSUE THREAD

**Issue by RichiH** [pretalx/pretalx#1850]
### Problem and impact

When reviewing submissions and clicking "Skip for now" on the last open review, I am put back into the main overview and see this:
![image](https://github.com/user-attachments/assets/c107790d-2f21-42aa-bfa3-2e4173a439b9)

So it somehow marked that last missing review as both done and still open.

### Expected behaviour

Not see the "Nice, you have no..." message.

### Steps to reproduce

1. Review proposals until only one is open for review
2. Click "Skip for now"
3. See above

### Browser (software, desktop or mobile?) and version

Chromium Version 125.0.6422.60 (Official Build) built on Debian trixie/sid, running on Debian trixie/sid (64-bit)

### Operating system, dependency versions

A mix of Debian sid/testing

**Comment by rixx** [comment]
Yeah, sorry, that's kinda intentional / not really solvable. "Skip for now" is a temporary measure for when you go through all your reviews one by one. When you do that, you get a semi-random proposal next (sorted by least reviews, then shuffled), so we need to give people a semi-persistent option to not get certain proposals. But that doesn't change that the review is still open / to do, so this behaviour, while a bit odd, is kinda correct – you said you wanted to skip the review, so you did, and *in your current run*, you have no proposals left to review. But you also, more generally speaking, still have got one proposal to review.

Notably, skipping a review is different from *formally abstaining*, which is only possible when organisers permit "no vote" reviews.
