### ISSUE TITLE
Show unconfirmed talks in schedule

### ISSUE THREAD

**Issue by jmlich** [pretalx/pretalx#1858]
### Problem and impact

I am preparing schedule, but talks which are not confirmed are not visible.

### Proposed solution / feature

Ideally, I would like to see talk in schedule even if not confirmed (there could be some icon to indicated its state)

**Comment by rixx** [comment]
Accepted, but unconfirmed talks can be scheduled. They will not show up in the public schedule, but they can be placed in the schedule editor. Like you suggested, they are coloured differently in order to make their different status clear. Even talks that are not accepted yet, but marked as pending accepted, can be scheduled.

**Comment by jmlich** [comment]
I mean, there should be an checkbox to show them in public schedule. I mean the conference it self will be held in two weeks. I have just published the schedule, but more than half is not confirmed. I can confirm talks manually and get it visible in the schedule, but I will loose the information who actually confirmed attendance. On the other hand, I want to have schedule publicly visible with all talks on the website to be able spread some noise on social networks.

**Comment by rixx** [comment]
You can set the talks as "featured" and direct people to the list of featured talks, but adding this setting would be quite a maintenance burden, which I would only add if somebody contributed it in a well-thought-through fashion.
