### ISSUE TITLE
Set users as coordinator of a talk

### ISSUE THREAD

**Issue by jaschaurbach** [pretalx/pretalx#1899]
### Problem and impact

Scenario: We have a conference with about 140 talks at the event. While the conference is running suddenly questions regarding the talk/the speakers occur which needs to ba answered/decided by the person who had the conversations with the speaker. 

### Proposed solution / feature

To every talk a coordinator can be assigned. This is viewable by the staff running the conference

### Context or examples

Example: Speaker asks for travel reimbursement and says that it was discussed prior. Unfortnualty there is no Emailtrail. The staff asks the coordinator what was discussed and agreed on.

**Comment by rixx** [comment]
I feel like this may be better off as a plugin – it seems fairly conference specific, though I know that @johanvdw has built something similar for FOSDEM.

I think the issue is that every event handles these things differently, and building this feature would open a fairly big can of worms. Off the top of my head:

- you’re asking for one coordinator, but I imagine that the next feature request will be for multiple coordinators
- we’d need to add filters for "proposals coordinated by you" in all the places
- we’d probably need email placeholders for proposal coordinators
- we’d need to decide if speakers are allowed to know who their coordinator is, and if so, if they should be asked to contact the coordinator rather than the organisers
- we’d need to decide if coordinators should be CC'd or BCC'd in all emails sent to "their" proposals (and how to deal with emails that are sent per-speaker, not per-proposal, because speakers will end up with different coordinators if submitting multiple talks)
- should coordinators be notified when they are assigned a talk? if so, we’d need a template and figure out how to not be terribly spammy about it
- do coordinators have a separate role, permission-wise? our permissions are a mess already, and adding a further distinction separate from "is a reviewer" would be a lot of work, but presumably, coordinators might need more edit permissions, but only for proposals that they own
- on that note, is "can assign coordinator" a separate permission, or does it go hand-in-hand with submission edit permissions, or settings edit permissions? + who is in the pool of coordinators that can be selected …


… and so on. I think I’d merge a good Pull Request contributing this feature (or work with a non-great PR until it is good enough, of course). But at the same time, it might be worth building this as a plugin first to figure out the answers to the questions above, and then merging it into core if wanted/needed.
