### ISSUE TITLE
Add speaker uploads

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#209]
Speakers may want to provide files for their submissions (their presentations, or extended reading material).

**Comment by meisterluk** [comment]
I am wondering, is there any source code in place preventing SVGs to be uploaded? Because we are experiencing this issue here (speakers cannot upload SVG files, but PNG works).

Maybe related to [submission.py](https://github.com/pretalx/pretalx/blob/master/src/pretalx/submission/models/submission.py)

**Comment by rixx** [comment]
No, SVG files should be fine, except in image uploads.
