### ISSUE TITLE
offer frab xml, ical and other formats in schedule export

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#280]
Our schedule export currently only exports the public HTML version. Since users also want to subscribe to ical and the other apps still want to download frab xml, even if the event organizers decide to only make the export available publicly, we need to export those as well.

- [x] add views in `src/pretalx/agenda/views/htmlexport.py`
  - [x] ical
  - [x] frab xml
  - [x] frab json
  - [x] frab xcal
  - [x] feed.xml
  - [x] talk ical
- [x] add those views to `BAKERY_VIEWS` in `src/pretalx/settings.py`

**Comment by rahmonov** [comment]
Hey @luto, is anyone working on this task? Can I take it? If so, a little more explanation would be great. Thanks.

**Comment by luto** [comment]
@rahmonov there is currently nobody working on this, so I'm happy if you'd take it on :) I'll add more explanation tonight (GMT+1).

**Comment by luto** [comment]
Sooo.. in addition to the normal HTML view (`/event/schedule`), pretalx also offers exports as ical (`/event/schedule.ical`), frab xml (`/event/schedule.xml`), frab json (`/event/schedule.json`), frab xcal (`/event/schedule.xcal`) and an atom feed (`/event/schedule/feed.xml`). There is also one ical file for each talk (`/event/talk/PEG83L/ical/`). There links are currently 404 in [the HTML export](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/management/commands/export_schedule_html.py).

The HTML view is already exported via [`ExportScheduleView`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/views/htmlexport.py#L37) and [`ExportScheduleVersionsView`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/views/htmlexport.py#L45). This needs to be replicated for each of the alternative format views within [`agenda/views/schedule.py`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/views/schedule.py). All resulting, new classes then need to be added to [`BAKERY_VIEWS`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/settings.py#L409), as well as [some tests](https://github.com/pretalx/pretalx/blob/master/src/tests/functional/agenda/test_schedule_export.py#L101).

I hope this makes things clearer and gives some pointers. Feel free to ping me with any open questions.

**Comment by rahmonov** [comment]
Hey @luto, thanks for the explanation. I was out sick last week, just getting better. Sorry for the delay. 

When I try to build by doing "python manage.py build", it raising a KeyError:

    File "/Users/jahongirr/OSProjects/pretalx/src/pretalx/agenda/views/htmlexport.py", line 13, in __init__
    self._exporting_event = kwargs.pop('_exporting_event')

    KeyError: '_exporting_event' 

Is there anything I need to do first?

**Comment by luto** [comment]
Oh, dang. I should write up some documentation for that thing m) You need to use `export_schedule_html` instead of `build`. [I added a proper error message](https://github.com/pretalx/pretalx/commit/bbc9ced06608a51831d08e30da96c528811602ac) to catch this in a friendlier way.

**Comment by rahmonov** [comment]
I am having a little trouble exporting FrabJson. We want the json url to be `/event/schedule.json` and for that we need `get_url()` of `BuildableDetailView`. Also, we need to override `render_to_response()` in order to return `JSONResponse`. However, this method is not called in `BuildableDetailView`. If we use `BuildableDetailView`, `render_to_response` will work but we won't have `get_url()`. We will have to set `build_path` statically. Any advise would be greatly appreciated. Thank you.

**Comment by luto** [comment]
Sorry for the late answer. I am not quite sure I understand the problem correctly :/ `BuildableMixin.get_content()` (from django-bakery) calls `self.get(self.request).render()` and `FrabJsonView` returns a response object in `get()`, so the following render call should correctly render that out as plaintext. But maybe I am mistaken.

Have you got a (non-working) state of your work so far somewhere so I can take a deeper look?

**Comment by rahmonov** [comment]
@luto yes, here: https://github.com/rahmonov/pretalx/blob/master/src/pretalx/agenda/views/htmlexport.py#L64

The problem is that its output is plain text, not json:
![image](https://user-images.githubusercontent.com/9026972/34079221-e8a921da-e34a-11e7-8ff8-d9ab70deea55.png)

Whereas, it should look like this:
![image](https://user-images.githubusercontent.com/9026972/34079223-f89292e8-e34a-11e7-883a-8974a12ad919.png)

The reason is that its content-type is not JSON. And the same thing with exporting ICal view. It would just output it as a plain text instead of downloading. The problem is again that its content-type is not `text/calendar`. 

In order to change the content type, I tried overwriting `render_to_response()` method, as explained [here](http://django-bakery.readthedocs.io/en/latest/commonchallenges.html#building-json-instead-of-html). However, this `render_to_response()` is not called with `BuildableDetailView`. It is ,however, when we use `BuildableTemplateView`. The problem with `BuildableTemplateView` is it does not have `get_url()` method which would allow us to dynamically set the url of the view.

I hope I did not confuse you :) 

Any help would be appreciated. Thank you.

**Comment by luto** [comment]
This looks like everything is fine, but the data is written to the file `jpqr2017/schedule.json/index.html` instead of `jpqr2017/schedule.json`.

Overriding `BuildableDetailView.get_build_path` _should_ do the job correctly, I am no not mistaken. By default that method takes the URL and appends `/index.html` to make the pretty django url available to webservers, which do not know anything about the URL structure. Skipping that should make bakery write to `jpqr2017/schedule.json` directly, which is what you want.
