### ISSUE TITLE
schedule.{json,xml,…}/feed.xml publicly visible even if schedule is not public

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#349]
schedule.{json,xml,…} publicly visible even if schedule is not public

**Comment by luto** [comment]
This is no longer the case for schedule.*; probably got fixed as part of the new exporter infra. I've added a test to validate this in d253c9d282a761a4bcec3165b1bdc0e4f9a46fe9.

However, the `feed.xml` is still affected. Since this is a function based view, I couldn't get it to work with our `PermissionRequired` class/mixin.
