### ISSUE TITLE
Add a plugin for additional static pages

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#369]

**Comment by MacLemon** [comment]
Ideas for static pages:
- Conference venue, pix
- How to get there, with maps, public transport information, where to get tram tickets
- Publishing a Code of Conduct
- Publishing Contact and Emergency information

Would probably make sense for formally aggregate parts of that information so that Apps/API clients can access that information in a machine readable manner to display them as well.

These pages should be published as part of the static Fahrplan export as well.

**Comment by rixx** [comment]
We're moving all plugin ideas from the issue tracker to [this page](https://github.com/pretalx/pretalx/wiki/Plugin-ideas/).
