### ISSUE TITLE
Link to video recording in schedule

### ISSUE THREAD

**Issue by laf0rge** [pretalx/pretalx#423]
It would be useful to be able to enter a link for each talk which points to the URL of the video recording, and which will be shown in the schedule (HTML and all export formats)

**Comment by rixx** [comment]
pretalx already has a hidden feature (hidden as in: functional only for media.ccc.de and there is no GUI) that embeds the talk recording in the schedule page. Since for all providers apart from media.ccc.de (where we use their API to match talks) URLs would have to be added manually, I haven't thought of a good UI for this yet. Examples for the embedded player can be seen [here](https://talks.mrmcd.net/2017/talk/ZZEFRH/)

**Comment by laf0rge** [comment]
ah, media.ccc.de is sufficient for my use case. Now I just need to figure out how to enable it. (Talks are not yet up on media.ccc.de, but will be soon).

**Comment by rixx** [comment]
Currently that's only possible from a python shell. From within your environment/however you call pretalx commands:

```
python -m pretalx shell
from pretalx.submissoin.utils import fill_recording_urls
fill_recording_urls(event_id, event_slug)
```

`event_id` is the id assigned on media.ccc.de (something around 140 currently I think), `event_slug` is the slug on your pretalx instance.

**Comment by laf0rge** [comment]
as an update, with pretalx 0.8.0 this has changed to:
`from pretalx.submission.utils import fill_recording_urls`

Also, pretalx 0.8.0 is required for current media.ccc.de due to commit 63be94aeca2ad30f74b812d84b60388887b09d53 which unfortunately has a rather non-descript commit message :/

**Comment by rixx** [comment]
That commit was made due to changes in the API, which doesn't come with announces or anything similar, leading to sometimes-frustrating searches for fixes. We can't reliably guarantee compatibility with media.ccc.de in old pretalx versions if they change their interface out from under us. Apologies for the commit message, though.

**Comment by rixx** [comment]
We can't guarantee compatibility with APIs that change without announcements or compatibility, I'm afraid – this also makes the search for the issue sometimes frustrating, hence the lackluster commit message (sorry for that).

**Comment by rixx** [comment]
Video recordings can now (after v0.8.0) added via plugins. The currently hidden inbuilt feature is deprecated, as it could only be used for media.ccc.de anyways. Instead, there is [pretalx-media-ccc-de](https://github.com/pretalx/pretalx-media-ccc-de), a plugin with a frontend for settings and everything.
