### ISSUE TITLE
Feature Request: Allow submitter to specify non-standard "Duration"

### ISSUE THREAD

**Issue by laf0rge** [pretalx/pretalx#427]
The "orga/admin" view of a given submission has the option of entering a talk duration that differs from the nominal/default duration specified for th event type.

It would be great if the actual submitter could also have write access to that field during the submission, so he can request a timeslot that exactly fits his requirement.

**Comment by rixx** [comment]
We originally decided against that, and I'm not sure the reasoning has changed: Adjusting the duration of a talk opposed to a default talk length should be up to the organisers, not the speakers. Requests can be done via the "Note to the organisers" field, and I'm not sure a more technical solution would help all that much.

**Comment by laf0rge** [comment]
I really don't want to sound rude or disrespectful, but I think it boils down to a mostly philosophical one: 
Do you as pretalx want to impose policy on event organizers on how they plan their schedule/events, or do you want to provide a tool that can be used flexibly in possibly different ways, by conference organizers with different event structures.  For the conferences I'm involved in, it makes a lot of sense to have the speaker specify the exact duration that he wants to talk.

As a speaker at many conferences, I can also confirm that I have seen CfP forms before where I was able to request a given event duration, so it's not as exotic as one might think.

Sure, you can write anything in the text comments, but that's unstructured information. It can easily be overlooked.  And if there's already a structured field in the obiect/database model, one might as well use it from the very beginning.  Also, even if I as the organizer would then change the duration field, I think the actual submitter will still not see the modified duration of his talk until there is a schedule released (I may be wrong here, sorry).

Creating different event types with 10, 15, 20, 30, 45, 60, ... minutes is of course another work-around, but I think it would also be just that: A work-around while a real solution already exist.

If you're running a large event with a very fixed timeslot structure, and you expect lots of mobility between the tracks, then of course you are less likely to use such a feature.  However, at smaller events, or events that have less/low mobility of audience between tracks, I find it very useful to have fine-grained slot durations, rather than trying to find "one size fits all" kind of solutions.

**Comment by rixx** [comment]
First off, there is nothing rude about a discussion. I didn't close this issue on purpose, as I wasn't yet sure how to continue with it.

The thing I'm mostly concerned with here is that changing the duration of a submission as a speaker will change the (next published) schedule, potentially without the organiser noticing. This has lots of potential to go wrong.

And sure, pretalx tries to work for as many different conferences as possible, but at the same time, having many configuration options for little stuff like this is horrible for user experience. We already have toggles for "ask for abstract/description", and "ask for biography", adding another one for "let speakers determine their talk length" seems very tedious.

Don't get me wrongt: I'm not opposed to the feature per se, I just haven't found the way to introduce it that I feel happy about.

**Comment by rixx** [comment]
Adding an option for this would be easier now that we have a tabular approach to the whole "what should speakers submit" area, but the issue with speakers changing the duration of their talk on the fly remains.

With the current implementation, once the talk has been scheduled, if the speaker changes the duration, the duration will not be changed in the current schedule **or any future schedule, unless the talk was moved** (because moving the talk leads to a recalculation of the talk's slot). Clearly, this is not sane behaviour.

The best implementation would be to always update the length of the *work in progress* talk slot for a talk when the talk is saved – as this is a bit of a lower priority to implement, I'll leave the ticket up for grabs for now.

**Comment by rixx** [comment]
Come to think of it, it might be easiest to let speakers specify talk duration on submission time, then leave the field read-only afterwards? That should be an easy compromise, as I guess organisers would want speakers to contact them if their talk duration changes.

**Comment by laf0rge** [comment]
On Sun, Feb 24, 2019 at 01:27:05AM -0800, Tobias Kunze wrote:
> Come to think of it, it might be easiest to let speakers specify talk duration on submission time, then leave the field read-only afterwards? That should be an easy compromise, as I guess organisers would want speakers to contact them if their talk duration changes.

read only for the submitter, yes.  But organizers should of course be able to change
it as required.

-- 
- Harald Welte <laforge@gnumonks.org>           http://laforge.gnumonks.org/
============================================================================
"Privacy in residential applications is a desirable marketing option."
                                                  (ETSI EN 300 175-7 Ch. A6)

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

The duration of a submission is usually determined by the submission type, but submissions have a field to override the default duration. Currently, this field is only visible in the organiser backend. pretalx already allows organisers to opt in/out of many submission fields for the CfP workflow, which the custom duration should be added to.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The fields available during the CfP workflow are set via event settings. The defaults can be found in `pretalx/common/models/settings.py`, and the modification happens via the `CfPTextDetail` view in `pretalx/orga/views/cfp.py`, and the `CfPForm` in `pretalx/orga/forms`.

Next, you'll have to add the field to the `request_require` list in `pretalx/submission/forms/submission.py`, plus the `fields` array (but **not** in `pretalx/orga/forms/submission.py`, as we want this attribute to be always visible to organisers). This *should* be all that is required, but please test that this actually works.

Bonus points if you decide to add a custom widget for this field that allows a split input of hours and minutes instead of just minutes.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.
