### ISSUE TITLE
CSRF Token Fail on Submission

### ISSUE THREAD

**Issue by thomersch** [pretalx/pretalx#520]
## Expected Behavior

As a user I want to submit a talk abstract, which takes a while to type. I want to do this and submit the talk afterwards.

## Current Behavior

CSRF times out. If you step back to the submission page and try to submit again, it fails as well.

## Steps to Reproduce

1. Open Submission form page
2. Wait for a while and submit
3. Watch it fail

## Your Environment

* Safari 11.1.2
* FOSSGIS 2019 conference

**Comment by rixx** [comment]
I could not reproduce this, and I can't quite understand why this would happen, unless you closed your browser in the meantime or touched your browser cookies otherwise (either manually or via a browser plugin). As Django CSRF tokens present sensible defaults and I've never encountered this behaviour, I'll close this issue for now, and will reopen it if the issue resurfaces.

**Comment by lucaswerkmeister** [comment]
I got this issue earlier today ([screenshot](https://twitter.com/LucasWerkmeistr/status/1200374149216120834)) – I think it was due to editing two submissions in separate tabs: after finishing the first one, the second one failed.

However, I wasn’t able to reproduce this afterwards; more specifically, after finishing the first step (out of three – talk details, why is this a good fit for us, profile details) in the first tab, the second tab did not result in a CSRF error. It’s possible that the CSRF token is only invalidated after a submission is completed (all three steps), but I didn’t want to try that out on https://cfp.verschwoerhaus.de/36c3/ – do you have a public test instance or something similar?

**Comment by rixx** [comment]
Hmm, so the issue most likely is that Django rotates CSRF tokens after login, so if you logged on during the first submission process, and then tried to submit a pre-loaded form, this would happen.

I'm not sure there is anything to be done here: The behaviour exists for security reasons, and since using the back button will keep all data in place, … that may be the best we can do with sensible amounts of effort. We *could* change the behaviour on CSRF failure in select cases, and I'd definitely be up to discuss a PR doing so, but I'd also tend towards caution, seeing as this is an issue with potential security impact.

**Comment by lucaswerkmeister** [comment]
Yeah, I don’t think you should change the behavior so that the request would be accepted – just a more helpful error message would be nice (such as the one added in 089d4fbcd5f73e7d48a49c5a3269cf610aaf6613 + 1ccdc514303d957fa5af010fc067d7fe727cd9cd).

Even nicer would be re-showing the form with the values that were just POSTed already pre-filled, so the user can immediately submit it again, but that would take a lot more effort to implement if it’s not already provided by some framework.
