### ISSUE TITLE
Describe creation of virtualenv in installation documentation

### ISSUE THREAD

**Issue by robbi5** [pretalx/pretalx#549]
The installation documentation uses in the systemd service files paths from a virtualenv which did not get setup before.

**Comment by rixx** [comment]
You're right, the systemd files should of course use the user environment instead of a virtual environment. This will probably not be terribly helpful to you right now, but we have a used and maintained pretalx ansible role here: https://github.com/pretalx/ansible-pretalx/, with service files here: https://github.com/pretalx/ansible-pretalx/blob/master/templates/pretalx.service.j2

**Comment by rixx** [comment]
Closed in f9bf7966 a few days ago.
