### ISSUE TITLE
Separate profile and account page

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#573]
## Problem you are facing

The current profile page `<event>/me` contains both, the profile and the account information. For me it was confusing that there are two save buttons on the page.

## Possible Solution

Separating the two into separate pages. Perhaps making the profile the default, with a link to the account settings.

Separating the two would also have the benefit that the account settings, which are global and not per conference, could e.g. be at a root url and not at an `<event>` one.

## Context

I was adding my name, but pressed the save button for the account,which then required to enter the password, but obviously didn't save the name.

**Comment by vmx** [comment]
I just found out that also the name is global. So if a separation is done, it might make sense to split it into global and per event settings (I'm not sure about it though).

**Comment by rixx** [comment]
Names and biographies are global, yes, so that speakers don't have submit them over and over.

Moving those settings to a global URL won't be easily possible, I'm afraid, as this would break with events with custom URLs, or at least would make both application and webserver configuration more complex and brittle.

Regarding the issue you mentined in the beginning, we could separate the two parts more, and make the password changing more obviously separate from the rest.

**Comment by vmx** [comment]
Biographies are separate (which I think makes sense, you might want to use a different bio for a different event).

If the separation is complicated, then it shouldn't be done :)

Perhaps also some help text would help, so you know which parts of profile page are global and which ones are per event. 

PS: (kind of off-topic) I'd like to mention that I find it quite confusion having the separation between events and orga, but then also some overlap. Perhaps having clear separation is something for a pretalx 2.0 :)

**Comment by rixx** [comment]
I added a note to the speaker name field that it's global. I'd say that's enough for now, and if more reports of confusion come up, we'll revisit the issue.
