### ISSUE TITLE
Missing time stamp offset in <day> elements in schedule.xml

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#618]
The[ FOSSGIS conference 2019 in Dresden](https://www.fossgis-konferenz.de/2019) uses a [Pretalx instance](https://pretalx.com/fossgis2019/schedule/).

## Current Behavior
In the [schedule.xml](https://pretalx.com/fossgis2019/schedule/export/schedule.xml) I noticed that the date format for a <day> element changed:

``` xml
<day date="2019-03-13" end="2019-03-14T03:59:00" index="1" start="2019-03-13T04:00:00">
```
Here the `+01:00` is missing which is present in `<date>` elements, e.g. `<date>2019-03-13T13:00:00+01:00</date>`.

## Expected Behavior
The format which was used at [35C3](https://events.ccc.de/congress/2018), e.g. [ChaosWest](https://fahrplan.chaos-west.de/35c3chaoswest/schedule/) and before and looks like this (modified example for above):

``` xml
<day date="2019-03-13" end="2019-03-14T03:59:00+01:00" index="1" start="2019-03-13T04:00:00+01:00">
```

## Context
This format change breaks the [EventFahrplan parser](https://github.com/EventFahrplan/EventFahrplan/blob/master/network/src/main/java/info/metadude/android/eventfahrplan/network/serialization/FahrplanParser.java#L155).
For the moment I can patch the issue in the app for the FOSSGIS conference. A fix is **not** urgent. It would nice if you can make sure the format is consistent in future instances of Pretalx.

## Your Environment

* Version used: 0.9.0 (judging from the comment in the XML file)
* Link to your instance, if in production: https://pretalx.com/fossgis2019/schedule/

# Related
- [Mixed time stamp offsets in <date> element in 35c3 in everything.schedule.xml](https://github.com/voc/schedule/issues/35)

**Comment by rixx** [comment]
Apparently we broke day break localisation a while back, sorry about that!

As for validation: This is a bit of a difficult topic. pretalx supports the `schedule.xml` format for interoperability, but it's a bit of a fight, especially since we're just trying to keep up with implementation changes at frab as they happen. We've decided, for consistency and our peace of mind, to take the VOC interpretation of the schedule.xml as single source of truth. Hence we have tests running against their schedule.xml definition at https://github.com/voc/schedule/blob/master/validator/xsd/schedule.xml.xsd. So it would be best if you could add time zone validation to that file, so that we're all on the same page.

**Comment by johnjohndoe** [comment]
I met to @saerdnaer at the FOSSGIS conference. He told me that Pretalx used an outdated version of the XSD. @rixx, am I right, that therefore no further action is needed by me to prevent this issue in the future?

**Comment by rixx** [comment]
That's correct – I completely forgot to update this issue. The Travis CI test runner now includes a test that checks if pretalx is on an up to date version of the schedule.xsd.

**Comment by saerdnaer** [comment]
@johnjohndoe 
>  He told me that Pretalx used an outdated version of the XSD.  
Actually @sophieschi was the one who told you that. 🤓
