### ISSUE TITLE
Email sending issue with STARTTLS

### ISSUE THREAD

**Issue by zoff99** [pretalx/pretalx#631]
## Current Behavior
send any kind of email. for instance invite new team members.
sometimes the email is listed in the outbox for sending,
sometimes it is not. kind of random if it works or not
even worse is when you want to reset your password and you do not get the email.

## Expected Behavior
send any kind of email. for instance invite new team members.
email should be listed in outbox for sending.

## Error log

we are using a custom SMTP server with STARTTLS config option set.
if it does not work its always the same error:

```
Traceback (most recent call last):
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/common/mail.py", line 115, in mail_send_task
    backend.send_messages([email])
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.6/smtplib.py", line 1030, in __init__
    source_address)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 1038, in _get_socket
    server_hostname=self._host)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/pretalx/.local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/common/mail.py", line 118, in mail_send_task
    raise SendMailException('Failed to send an email to {}.'.format(to))
pretalx.common.mail.SendMailException: Failed to send an email to ['**redacted**'].
```

## Your Environment

* Version used: v0.9.0
* Environment name and version: firefox browser
* Operating System and version (desktop or mobile): debian 9 vanilla
* self compiled python3.6 (the recommend binary package does not exist)
* mariaDB with utf8 (otherwise there is an error on install)

**Comment by rixx** [comment]
It seems this is not a pretalx specific error, and your environment does not work with the SSL your mail server uses. ``ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)`` is a C level error, so the issue is not even with Python itself. Is your server restricted to using specific SSL versions? Can you provide context on the aborted handshake?

> the recommend binary package does not exist

Yes, sorry for this – I just removed all Linux flavor dependent documentation yesterday to avoid issues like that in the future – judging from the feedback I got, it seems better to leave people to figure out Python 3.6 on their own.

> mariaDB with utf8 (otherwise there is an error on install)

Feel free to submit a documentation PR! I don't usually use MariaDB, so I wasn't actively aware that there were still DB systems out there that don't run with utf8 by default.

**Comment by zoff99** [comment]
it would be best to suggest what type of linux pretalx is best to install (debian 9 or debian 10 or something), then people can use that one

**Comment by zoff99** [comment]
```
Is your server restricted to using specific SSL versions? Can you provide context on the aborted handshake?
```

the strange thing is that sometimes it works and sometimes not. without changing any config.
just try again an then it may work.

for password resetting it never works though

**Comment by rixx** [comment]
> the strange thing is that sometimes it works and sometimes not. without changing any config.
just try again an then it may work.

I'm afraid without further debug information it will be very hard to pin this one down.

> it would be best to suggest what type of linux pretalx is best to install (debian 9 or debian 10 or something), then people can use that one

I'm not prepared to do that – I use no Debian style Linux, myself. Previously I merged documentation contributions by people using those systems, to help others. But since those run out of date with me noticing, and then we're being told that pretalx is useless and the documentation sucks, it's better to restrict ourselves to the fact: Installing pretalx requires a certain environment, such as a database and specific Python versions, and it's up to the administrators to provide this environment.

**Comment by rixx** [comment]
Do you have any further information to help debugging this?

**Comment by knarrff** [comment]
With STARTTLS the initial connection should be made clear-text and only after that. Would you try to use ssl from the start (in this context often the difference between starttls and ssl/smtps), you would get the above error message, because the clear-text is interpreted as ssl version number, which will not work.

Maybe double-check that the configuration option is correct (STARTTLS vs. SSL), and also don't necessarily trust those port numbers to correspond to the (587/465)-pair.

That would not explain that you described this as sometimes working and sometimes not, though.

As for the python version: being limited to 3.6 (not 3.5 and not 3.7) is an unfortunate choice for users of Debian, as there is no Debian version that provides native packages for version 3.6. The current 'stable' goes up to 3.5, while the next will only contain 3.7 (and possibly newer versions as backport).

**Comment by rixx** [comment]
> With STARTTLS the initial connection should be made clear-text and only after that. Would you try to use ssl from the start (in this context often the difference between starttls and ssl/smtps), you would get the above error message, because the clear-text is interpreted as ssl version number, which will not work.

We let the libraries take care of that.

> Maybe double-check that the configuration option is correct (STARTTLS vs. SSL), and also don't necessarily trust those port numbers to correspond to the (587/465)-pair.

I'm not sure where you think we assume ports? pretalx allows to configure mail server ports separate from the protocol option.

> As for the python version: being limited to 3.6 (not 3.5 and not 3.7) is an unfortunate choice for users of Debian, as there is no Debian version that provides native packages for version 3.6. The current 'stable' goes up to 3.5, while the next will only contain 3.7 (and possibly newer versions as backport).

This is a very different issue, please let us keep it out of it. When the last pretalx release came out, one of our dependencies was not ready for Python 3.7 (I think you knew that?), which is not something we can change. The next release will be Python 3.7 compatible. If Python 3.7 support is this important to you, you can run off the master branch, or by installing a later version of Celery manually. Directions for running a development version in production [can be found in our docs](https://docs.pretalx.org/en/latest/administrator/maintenance.html#installing-a-commit-or-a-branch-version).

**Comment by knarrff** [comment]
> We let the libraries take care of that.

I do see the option to select STARTTLS and/or SSL in pretalx.

> I'm not sure where you think we assume ports?

Not assume, but suggest. For example, for STARTTLS, pretalx tells me "Meistens auf Port 587 verfügbar." (commonly on port 587). This is correct and nice from Pretalx, but if you do have problems like here, it could be that the specific smpt-server in question here does not follow these common port numbers.

> This is a very different issue

Agreed. And I am sorry if this sounded like a complaint. I appreciate the usually very fast reaction times on issues here *a lot*. Big thanks! I can totally understand the reasons behind the current dependencies and might have done the very same. Dependencies are a blessing when it means you can build on them, but they can be a pain, too.

**Comment by rixx** [comment]
> I do see the option to select STARTTLS and/or SSL in pretalx.

Exactly – this choice is then handed off to the library handling mail transfer.

**Comment by rixx** [comment]
Closed as stale.
