### ISSUE TITLE
Add editable granularity of schedule times

### ISSUE THREAD

**Issue by sdruskat** [pretalx/pretalx#639]
## Problem you are facing
I'd like to make rooms available in 15 minute intervals rather than the predefined 30 minute intervals.

## Possible Solution
Introduce a feature that allows the setting of interval times for the schedule, so that sessions can be defined going from, e.g., 18:15 to 19:25. 15 minute intervals would suffice as a strating point I guess as this will most likely suit the highest subset of events.

**Comment by rixx** [comment]
I'm not sure I understand what you're asking – you say that "sessions can be defined going from 18:15 to 19:25", but that's possible already. The only thing that's not possible is editing room and speaker availabilities on this basis.

My main issue with moving this to 15 minute intervals is that for very little gain (because the availabilities are only there for the planning stage, and do not constrain the actual scheduling), the availabilities editor would become much more annoying to use, due to its doubled length:
![Screenshot_2019-03-26 MV pretalx](https://user-images.githubusercontent.com/2657547/55003050-e6c8e800-4fd7-11e9-9e59-c093fa1a81b0.png)
![Screenshot_2019-03-26 MV pretalx(1)](https://user-images.githubusercontent.com/2657547/55003053-e92b4200-4fd7-11e9-925b-5cda9b3a4fc8.png)

**Comment by sdruskat** [comment]
Okay, I see what you mean. No need to sacrifice usability for (unneeded) precision in this case.
