### ISSUE TITLE
Schedule editor does not scroll while dragging talk

### ISSUE THREAD

**Issue by schwindp** [pretalx/pretalx#640]
## Current Behavior
When scheduling talks you cannot "drop" them on a date & time that's not show on the screen. Even when dragging the to-be-scheduled talk towards the northern or southern screen bounds, pretalx doesn't scroll.

## Expected Behavior
Being able to drop a talk on a date/time that's not right now show on the screen. Pretalx should scroll the screen to show other available timeslots.

## Steps to Reproduce

1. Have a schedule that doesn't fit on your screen
2. Try to schedule a talk onto a timeslot that's not shown on your screen
3. won't work.

## Context
To make it a bit easier to accomplish scheduling I made the browser scale down to see more timeslots at once. 

## Your Environment

* Version used: v0.9.0
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome 72
* Operating System and version (desktop or mobile): Windows 10
* Link to your instance, if in production:

**Comment by rixx** [comment]
Writing drag/scroll controllers is pretty annoying, so if anybody wants to take this up, I'm happy to merge a PR! 

Personally, I'm so used to scrolling with either my mouse wheel or my arrow keys when dragging something that I didn't even notice this missing feature, because dragging stuff towards borders always feels so clunky to me. You are of course right, though, and pretalx should support this.
