### ISSUE TITLE
Lost submissions because login/registration box is slow to load.

### ISSUE THREAD

**Issue by katharosada** [pretalx/pretalx#646]
## Current Behavior

When a not-logged-in user creates a talk submission, they reach the `Account` page where they are prompted to create an account or log in to an existing account.

Unfortunately, the login/registration boxes don't load quickly enough and there's no indication that something is loading. On my slow internet, it took at least 30 seconds to load. Before that happened, I assumed I was meant to click the `login` link in the top right corner. This other login page lost track of my submission progress and I was sad. :(

## Expected Behavior

1. The login and registration form should appear at the same time as page load so that people don't click the login link while they're waiting. Even a small loading wheel would make it better than it is now.
2. Ideally, going to the normal login/registration page should not lose progress anyway.

This is how it looks for a good 30-40s before it loads the login boxes:
![image](https://user-images.githubusercontent.com/4311392/55394780-ca0a5280-558b-11e9-8149-ab54ed74e49a.png)

## Steps to Reproduce

1. Be on slow Australian internet
2. Be logged out 
3. Submit a talk up until the account page.
4. The login/registration box doesn't load for about a minute so you click the little `login` link in the top right corner.
5. You're taken to the login/registration page which loses track of your almost completed submission.
You can never get that talk content back now.

## Context

For PyCon AU, we're going to see a *lot* of unhappy people who lose their talk submission and we have zero way to contact them about it. This is going to be a big deal for us.

## Your Environment
Chrome, Australian internet.

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:
https://pretalx.com/pyconau2019/cfp

**Comment by rixx** [comment]
Oh wow, this shouldn't happen. (Though your submission should still be there if you go back a step?)
Seems we need to optimize page load quite a bit here – apparently the culprit is the password complexity indicator, but as we haven't optimized js loading at all so far, there's a lot of room for improvement. (Just to make sure that this is the issue: loading problems were mostly present on that page of the submission workflow?)

I just pushed a commit that potentially fixes the issue (and makes other pages a bit faster, too). Could you have a look if this looks better for you now? It seems to have fixed the problem on my end, but I'm not in Australia (and I don't have a VPN available for tests atm).

**Comment by katharosada** [comment]
Much better! Thanks so much for the quick fix! The page loads everything at the same time now so it avoids the issue. :)
Side note: Going back a step doesn't work if you already clicked 'login' at the top right.

**Comment by rixx** [comment]
> Going back a step doesn't work if you already clicked 'login' at the top right.

Huh, it really should – the data is saved at the URL you had open, after all. I'll try to look into it!
