### ISSUE TITLE
Send templated email in "presenters' language"

### ISSUE THREAD

**Issue by sdruskat** [pretalx/pretalx#652]
Behaviour in FF 60.5.2:

I've noticed that when you send emails form the template page, all emails will be worded using the languaged template reflecting the current user's language choice. I.e., when
- the template is available in English and German, and
- the UI language of the current user - the one sending emails - is German:
the emails created from the template will always be in German.

It'd be great to have pretalx generate the emails in the language reflecting the settings the respective recipient has last, or a language that they can set in the user settings.

**Comment by rixx** [comment]
> when you send emails from the template page

By that, you mean the Mail Editor (at ~`mails/compose`), correct? At that point, no multi-language input is possible currently. E-mails sent from templates directly (such as accept/acknowledge/reject/update emails) will always be sent in the presenter's locale.

**Comment by sdruskat** [comment]
No, I meant clicking the "send email" button below a (custom) template. I created emails from this and went to edit them from the outbox, and they were all in just the one language, despite the fact that I know some recipients will never have accessed pretalx in that language.

**Comment by rixx** [comment]
> No, I meant clicking the "send email" button below a (custom) template.

… which should lead you to the mail editor at `~mails/compose`, so my point stands. It would of course be nice to be able to draft mails in multiple languages.

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides two models to interact with emails: `MailTemplate` and `QueuedMail` – you can read more details about them [here](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#emails-and-templates). Mail templates use [django-i18nfield](https://github.com/raphaelm/django-i18nfield) to provide multi-language input for the mail texts, but `QueuedMail` objects only have regular text fields.

The interface for writing emails without templates currently only provides a regular text field. Since this mail sending interface allows to address an arbitrary amount of people, it would be much better to provide internationalised input, and then choose the correct language locale per addressee.

## How to do get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

Look at the `pretalx/orga/views/mails.py` file. You'll find the correct view (``ComposeMail``) and the form used in there. Modify the form to use the i18n widgets, then in the view in the `for user in user_set` loop, activate the correct locale before creating the `QueuedMail` object.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment]
Emails are now sent in the language of the proposal they are sent for!
