### ISSUE TITLE
Users can see acceptance/rejections before they are released

### ISSUE THREAD

**Issue by ChrisRackauckas** [pretalx/pretalx#667]
## Current Behavior

While reviews are accepting/rejecting, participants who view the website can instantly see whether they were accepted or rejected. This is before the committee is able to back through and ensure the total numbers are okay.

## Expected Behavior

Participants shouldn't be able to see if they were accepted/rejected until the website releases this information (the email)

**Comment by rixx** [comment]
Generally, I agree, but I have yet to see

- a good data model
- a good workflow in terms of UI

So while I'm open for suggestions and (even more!) contributions, this ticket might stay open for a bit.

**Comment by Nakaner** [comment]
> The first step is to figure out the best data model to do this.
> 
> * Do we want to add another state to submissions? (I'd regard that as bad design, but I'm open for suggestions)

I agree.

> * Do we want a separate field public_state? This would have to be taken into account in the submitters' view on their submissions, and in permissions for actions like confirm and edit_submission.

Having public_state requires changing a lot of places in the codebase. Everywhere where state is used, one has to decide whether state or public state has to be used.

Is it maybe better to have a `state_hidden` field (default false). If `state_hidden` is true, the states accepted, rejected and confirmed are hidden and appear as submitted to the submitter. All other states appear as they are. From orga point of view, an acceptance will then require two steps. First the submission gets state=accepted + state_hidden=True. In a second step the organisers ask the submitter for confirmation by setting state_hidden to false (the UI could call this "announce acceptance"). This usually happens after the organisers decided their decisions on all submissions to be final.

**Comment by rixx** [comment]
That's a good approach, I think, and we should consider how to go with it. Email generation would presumably happen when the announcements are made, ie. the talk state is published.

My main concern here is the usability of pretalx. Generally, this action should be performed for all submissions at once, but we can't rely on that: Organisers might want to send out single acceptances first, or send out acceptances first, rejections later, etc. Having a good user interface for this will be really hard, and I'm not clear on it yet where those actions would go, and how to best make it clear when states are made public.

Considerations for the migration: We'd need to set the sensible default for all events that have already accepted or rejected submissions to have their states visible, and for all other events to have the states hidden, so that will be a bit annoying.

**Comment by rixx** [comment]
This feature has been taking shape in my mind, so here are some short notes to help whoever picks this up:

- Add a field `pending_state` to the `Submission` model
- Make sure it is only exposed in the organiser API
- Add a button to "perform all pending changes" to session lists
- Add a checkbox to make state transitions pending, both to the state change page and to the bulk accept/reject interface
- Add a method to `Submission` that calls the appropriate state change methods
- Add filters for pending states
- Add a visible warning (maybe a dot, maybe a counter like the unsent email one) when there are unapplied pending changes
