### ISSUE TITLE
Send e-mail to subset of speakers

### ISSUE THREAD

**Issue by vchuravy** [pretalx/pretalx#669]
## Problem you are facing

There are already several filters implemented for subset of speakers to send e-mails to as recipient groups. I want a bit finer granularity since I want to send an e-mail to specific to the type of the submission, e.g. to all workshop speakers.

## Possible Solution

Add more granular filters to mail editor or a general "query" system

**Comment by rixx** [comment]
While I understand your wish for this feature, I don't think this would be a good idea in pretalx core unless somebody comes up with a good UI interface for this type of query – so while I'd be open to discuss such a change, it would probably be a good idea to add this kind of functionality via a plugin.

I'll leave this issue open for a bit to see if any good UI proposals come in. If they don't, I'll close it and add it to the list of plugin ideas in the wiki.

**Comment by rixx** [comment]
Since there has been no proposal for a user interface more complex than the current one, I added email selectors by track and submission type, but all selected filters will be ORed. I'm willing to revisit this issue if somebody proposes a good UI for moree complex filtering. I also added this proposition to our [plugin idea list](https://github.com/pretalx/pretalx/wiki/Plugin-ideas).

**Comment by logankilpatrick** [comment]
Chiming in to say this would still be a nice feature. It is such a pain to have to export each workshops speakers email.

**Comment by rixx** [comment]
This is an upcoming feature – we found a sponsor, and will start development soon. Bigger features like this only really happen through sponsorship or outside contributions, so it can take some time until they are implemented.
