### ISSUE TITLE
Visible status of outgoing mail (when missing celery workers)

### ISSUE THREAD

**Issue by kannes** [pretalx/pretalx#692]
As I struggled with this a while ago I just thought I would log this as a feature requests and propose ideas.

I am probably mixing up terms badly. Workers, task runner, stuff like that. 

## Problem you are facing
I had followed https://docs.pretalx.org/en/latest/administrator/installation.html and failed to set up things as intended, see https://github.com/pretalx/pretalx/issues/680 and https://github.com/pretalx/pretalx/pull/681

I had added a `[celery]` section to my config but was not running any celery workers.
This led to mails not being sent with no error or notification visible to me.

I just tried this to successfully reproduce it:
1. Have a `[celery]` section to your config.
2. Stop any running workers (`systemctl stop pretalx-worker.service`)
3. Send a mail via pretalx' web interface

No mail will be sent. There are no errors in `journalctl -u pretalx-web` or `/var/pretalx/data/logs/pretalx.log`.

## Possible Solution
It seems like the running celery process IS actually collecting the outgoing mail but not sending it. It will be sent one the `pretalx-worker.service` runs again.

> May 07 12:52:15 pretalx-ubuntu-2gb-nbg1-1 celery[17575]: [2019-05-07 10:52:15,029: INFO/MainProcess] Received task: pretalx.common.mail.mail_send_task[stripped]
> 
> May 07 12:52:15 pretalx-ubuntu-2gb-nbg1-1 celery[17575]: [2019-05-07 10:52:15,935: INFO/ForkPoolWorker-1] Task pretalx.common.mail.mail_send_task[stripped] succeeded in 0.9005828551016748s: None

So I guess there is a way to query celery to see pending tasks. It would be great if this was exposed to the web interface as a list of currently pending tasks maybe?

Alternatively maybe a sanity check of the config could be done at runtime? If there is a `[celery]` section in the config but there is no available worker, tell the user about it.

**Comment by rixx** [comment]
> So I guess there is a way to query celery to see pending tasks. It would be great if this was exposed to the web interface as a list of currently pending tasks maybe?

Celery tasks cannot be inspected for content. All you can do is examine the queue length – what you're really looking for is a broker with more of a frontend than redis. AMQP is the Celery broker of choice for tasks such as that. Our setup documentation chooses redis because it is easy to set up and can also be used for other tasks, but if you want to dive deeper into a celery setup, you'll have to read the celery docs and their broker recommendations.

> Alternatively maybe a sanity check of the config could be done at runtime? If there is a [celery] section in the config but there is no available worker, tell the user about it.

I had looked into that when you reported your issue in the first place, but there is no trivial way to check for this. The only way that doesn't run into the danger of timeouts or blocking execution involves having a dummy celery task just for the sake of checking task execution (which would still be both complex and brittle).

**Comment by kannes** [comment]
Ah, dang. Thanks for checking it out. I shall live on now ;)
