### ISSUE TITLE
Can't withdraw after submission has been accepted

### ISSUE THREAD

**Issue by nassarhuda** [pretalx/pretalx#700]
## Current Behavior
After a proposal has been accepted, I can not withdraw my application

## Expected Behavior
I should be able to withdraw my application regardless

## Steps to Reproduce

1. create a submission
2. accept the submission
3. try to withdraw the same submission
4. you can only click "confirm"

Example: 

Page 1 after I log in:
![Screen Shot 2019-05-26 at 3 12 00 PM](https://user-images.githubusercontent.com/12686504/58387259-e3eb7300-7fd9-11e9-925a-e02f67cfd75c.png)

I click "confirm", next page:
![Screen Shot 2019-05-26 at 3 12 20 PM](https://user-images.githubusercontent.com/12686504/58387268-0087ab00-7fda-11e9-9570-017fc6f693e3.png)

I don't want to click "confirm", and there's no option to withdraw.

Our submitters who wanted to withdraw their application had to email us to ask us to manually remove their submission.

Thank you!

**Comment by rixx** [comment]
Currently, our logic is that once a submission has been accepted, organisers will want to be involved if the presentation can not be held, so to set an accepted or confirmed submission to "canceled" requires organiser interaction.

Especially on published talks I feel that changing this would be dangerous: As an organiser, you don't want your presenters to just retract their talk without telling you, modifying your schedule in the progress.

**Comment by ChrisRackauckas** [comment]
Where this seems to fall apart is when submissions change categories. As a follow up to https://github.com/pretalx/pretalx/issues/666 , in many cases a conference will not fully reject a presentation but change its category, i.e. downgrade from a talk to a poster. However, about half of the people who got downgraded simply withdrawal. It ends up being quite a burden to do all of those withdrawals manually.

Instead of an email conversation -> manual withdrawal -> email back, it would be much easier if it was withdrawal -> get email that person withdrew their submission.

>Especially on published talks I feel that changing this would be dangerous: As an organiser, you don't want your presenters to just retract their talk without telling you, modifying your schedule in the progress.

It shouldn't impact scheduling if we were allowed to set an time limit on confirming, i.e. don't confirm before X and your submission is withdrawn (which we seemed to need this year). That's probably another question though.

**Comment by rixx** [comment]
> Instead of an email conversation -> manual withdrawal -> email back, it would be much easier if it was withdrawal -> get email that person withdrew their submission.

An email notification would be mandatory, agreed.

> It shouldn't impact scheduling if we were allowed to set an time limit on confirming, i.e. don't confirm before X and your submission is withdrawn (which we seemed to need this year). That's probably another question though.

I don't think this is a good indicator. Instead we could say that talks may be canceled by speakers as long as they haven't been published in a schedule yet. I'll accept this issue on that basis, so whoever implements this will have to:

- Change the permission logic to allow talks to be canceled by speakers as long as they have not been published
- Add a cancellation option in the confirmation page
- Make sure that the organisers receive a notification via email when a speaker cancels an accepted/confirmed talk

**Comment by rixx** [comment]
![Screenshot_2019-05-31  foo](https://user-images.githubusercontent.com/2657547/58723419-4da0be00-83da-11e9-8a8b-432100592fc7.png)
