### ISSUE TITLE
Development environment is recreated with each tox command

### ISSUE THREAD

**Issue by rahmonov** [pretalx/pretalx#717]
## Current Behavior
Each tox command seems to recreate the virtual env folder (.env). 

I did `tox -e dev manage.py migrate`, it worked fine. Then, I did `tox -e dev manage.py init` and it fails by saying `The path /path/to/pretalx/.env/bin/python3.7 (from --python=/path/to/pretalx/.env/bin/python3.7) does not exist`. 

I checked the `.env` folder and there was only the `logs` folder.

It might very well be my inexperience with `tox` though. If so, my apologies.

## Expected Behavior
The `.env` folder should not be deleted and recreated if it already exists.

## Steps to Reproduce

1. tox -e dev manage.py migrate
2. tox -e dev manage.py init

## Context

I was trying to set up the development environment to make some contributions.

## Your Environment

* Version used: 1.0.0
* Environment name and version (e.g. Chrome 39, python 3.5): python3.7
* Operating System and version (desktop or mobile): macOS Sierra 10.12.6

**Comment by rixx** [comment]
We may just switch away from tox, to be honest – the `tox.ini` does include a `recreate = False`, so that looks like we're doing something wrong, and I'm not terribly sold on tox at this point.

Anyways, as you can run pretalx without `tox`, I'll close this issue – if you figure out what is wrong with our tox config, I'll be happy to merge a PR!
