### ISSUE TITLE
Show only relevant part of day in schedule editor

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#734]
## Problem you are facing
The schedule shows a full 24 hours per day.
This makes it harder to navigate and particularly drag and drop things around.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/5127634/60373699-01f12c80-99f9-11e9-9d90-015488d07f0d.png">

## Possible Solution
Allow a begin and end time to be set globally and crop those hours out of the schedule

**Comment by rixx** [comment]
That's a great idea, for sure! Instead of going by a configurable day length though, we could just use the time any room is available.

If anybody needs any support in implementing this, I'm happy to help – our availability data model is already capable of helpful arithmetics to determine which timeframes should be shown per day.

**Comment by rixx** [comment]
Since I have just done some work on the schedule editor, let me add some thoughts:

This feature would be way harder than it looks, since our current positioning of talks takes advantage of the continuous flow of, y'know, time. We just assume that every minute gets a pixel and determine talk positions from there. This would need to change, and not on day breaks either (because conference "days" can cross midnight thresholds).

**Comment by oxinabox** [comment]
Yeah, I think a layer of indirection needs to be done there.
For this and for other features relating to position and readability.

**Comment by rixx** [comment]
Closed via #1340
