### ISSUE TITLE
Ability to Submit, Confirm, and Schedule an event all at onces

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#738]
## Problem you are facing
I would like to, as the event organizer, be able to directly confirm and schedule talks on the submission page.

## Possible Solution
Add an option to the submission page,
that lets yet set the status of a submission,
and lets you set the time and room (like on the quick schedule page).

## Context
There are a surprising number of Program Items that need to be added directly by the organizer.
Where it is already certain to happen, and sometimes the times and rooms are already set.
Things where all the organisation of them has already happenned over email.

Examples include:
 - Openning/Closing Address
 - Invited Keynotes
 - Sponsor Talks
 - Birds of a Feather Sessions
 - Last minute program items via special request

Right now to add these the process is:
 1. Go to submissions page, click add submission
 2. Enter the submission details click submit
 3. Go back to the submissions page and change the status to Confirmed
 4. Confirm, on the confirmation page
 5. Go to schedule page and schedule it.

Visiting 5 pages to do this is a bit much

**Comment by rixx** [comment]
I do agree that adding editing input to change the time(s) and room(s) of a submission would be nice, and while adding this option isn't trivial, I'd welcome a submission of this option! I don't think this should be limited to the submission creation, either.

As for the submission state, it should be selectable upon submission creation (as an organizer), but afterwards, the actual action is required to perform the relevant action (and to make sure the user is really sure they want to change the state, as this can be a destructive action).

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx allows organisers to create submissions themselves in the organiser backend, without going through the complete submission workflow (e.g. to work around deadlines).

Organisers may want to set the state of these submissions directly to "confirmed", and schedule them to a certain time or room.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The View responsible for this is in `pretalx.orga.views.submission.SubmissionContent` – it is both used for updating and creating submissions. I would suggest changing the view so that it is only used for editing existing submissions, and add a new view for creating it. It should be mostly the same view (you can probably go ahead and use inheritance and the same template).

Use a different/inherited form, though, with the additional fields `state` (options: submitted/accepted/confirmed), `room`, and `start`. On successful saving, create the submission in the `submitted` state, and then use the `accept()` or `confirm()` methods as appropriate. If a room and time was also submitted, use something like `submission.slots.filter(schedule=event.wip_schedule).first()` to get the `TalkSlot` object, and assign the appropriate room and time. (Please test to make sure you're taking the event timezone into account!)

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by oxinabox** [comment]
Woot
