### ISSUE TITLE
If you enter an email address for a session that already has a speaker then the name is silently overwritten

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#739]
## Current Behavior
When creating a submission you must enter a Speaker Name and a Speaker Email.
If there is already a Speaker using that email, then the entered name is 
silently ignored and is replaced with that of the speaker matching the email

## Expected Behavior
Either: 
 - 1 email should be allowed for multiple different speakers, or
 - having a disagreeing name should give an error / prompt of "do you mean ...?" and should not let you proceed.

## Steps to Reproduce

1. Create a speaker with email `foo@example.com` and name `John Doe`
2. Create a Talk, set speakers name for `Jonathon Stag`, and email to `foo@example.com
3. Note that the name on the talk is `John Doe` 

## Context
I was trying to add a sponsor's talk to the system,
I didn't have a contact for the sponsor, so I was setting the speaker name to the sponsor name, and the email to our sponsor liaison, who would pass on what ever information mattered.

## Your Environment
* Environment name and version (e.g. Chrome 39, python 3.5):  Firefox 66.05
* Operating System and version (desktop or mobile): Windows Desktop
* Link to your instance, if in production:
https://pretalx.com/orga/event/juliacon2019

**Comment by rixx** [comment]
> 1 email should be allowed for multiple different speakers, or

Absolutely not, we use email as unique, identifying characteristic.

>    having a disagreeing name should give an error / prompt of "do you mean ...?" and should not let you proceed.

This isn't something we can really do, either, because this leaks who has an account on a pretalx instance in an exploitable way.

## Possible solutions

- Easiest: Accept any name, but to discard the name if a previous one exists.
   - Problem: Won't alert organizers that something is amiss.
- Most correct: Implement a proper invitation system, where all invites don't directly result in accounts created/etc.
   - Problem: Lots of complexity
- Easiest: Just send out an email link like when one speaker invites another to join.
   - Problem: Can't track who actually joined the talk / if there are still invites pending.
