### ISSUE TITLE
Better anonymized review

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#744]
It would be very good of pretalx to anonymize any submission texts (like abstract, description, and questions) in the view the reviewers see by filtering out any case-insensitive matches for the speaker's complete name and email address.

**Comment by vmx** [comment]
I'm not sure about this feature. It sounds pretty error-prone. Often authors might use middle name initials (in the name or then in the abstract) or the email address doesn't match the one of the account.

I personally would rather make sure that people don't put in information they can easily identified with (e.g. with good help texts or questions that can be hidden from the reviewers), rather than giving a false impression that it will automatically be anonymized.

**Comment by rixx** [comment]
To your first point of it being error-prone: How can it be? Its goal is not to provide completely anonymized texts (as that is clearly not possible for a computer), its goal is to **remove known bad strings** (especially the user's email address and full name).

Regarding your second point of false impressions: We wouldn't give the impression that anything will be automatically anonymised, because

a) we will not advertise this behaviour, and
b) even if we did, we would not do it this way.

I don't see any reason *not* to do this very simple and cheap check as a last-ditch effort of removing personal data. It might help in some cases, and if it doesn't, then we have not lost anything.

**Comment by rixx** [comment]
Instead, we are going to get proper anonymised reviews via #875
