### ISSUE TITLE
Add means to create personalised schedule

### ISSUE THREAD

**Issue by dpsanders** [pretalx/pretalx#748]
## Problem you are facing

There are parallel sessions and no way to make a personalised schedule.

## Possible Solution

Allow highlighting the schedule to select which talks to attend, and export that to a personalised schedule with times and rooms.

**Comment by rixx** [comment]
This is definitely a feature that is wanted and would be good to have!

It also comes with a whole bunch of considerations, and won't be trivial to build:

- How does this data get saved?
  - A user account? I'm rather against that, because less user data is better data.
  - Just localstorage? Sounds fine by me, but also means that organisers won't be able to gauge interest.
- How will the data be shared between devices?
  - Probably just a link, to be honest, but it might be nice to create permalinks for other users to look at, too.
  - Building a calendar export into this would mean a calendar lib in the JS component (or else, more work by the server, I suppose)

… and a bunch of other stuff I didn't remember right now. Proposals on those and other details are definitely welcome!
