### ISSUE TITLE
Saving an event with opened upload turns talk's page into 500.html

### ISSUE THREAD

**Issue by katrinleinweber** [pretalx/pretalx#797]
## Current Behavior

When a presenter of an already accepted & scheduled talk (under `…/me/submissions/…ID…/`):

1. changes it,
1. clicks the upload button, but
1. doesn't select a file, nor adds a description, and then 
1. saves,

this works apparently fine. However, the talk's page (`…/talk/…ID…/`) returns ["HTTP 500" error](https://github.com/pretalx/pretalx/blob/b0d14a51343c68778ac2a518df899e22d828e9d3/src/pretalx/common/templates/500.html).

## Expected Behavior

Unused upload form gets ignored and/or talk's page is unaffected 

---

* Version used: ?
* Environment name and version (e.g. Chrome 39, python 3.5): ?
* Operating System and version (desktop or mobile): ?
* Link to your instance, if in production: https://talks.hackover.de/ho19/

**Comment by rixx** [comment]
Hmm, I can't seem to replicate that behaviour atm, I suspect that more factors are at play. If you click the "Add another resource" button, but do not provide a description or a file, the submission shouldn't be able to be saved at all, since the field is marked as required:


![DeepinScreenshot_select-area_20191018190514](https://user-images.githubusercontent.com/2657547/67113614-41c36600-f1da-11e9-87b3-6b90571be462.png)

Could you provide more details? Otherwise, could you provide more details, or get the organisers to look at the server logs?

**Comment by katrinleinweber** [comment]
Yeah, I'll ask them. What you show occurs on the 2nd try of saving the form in their instance:

![image](https://user-images.githubusercontent.com/9948149/67123421-8fe36400-f1f0-11e9-9dea-1c7ef85b1508.png)

The 1st try after adding the empty upload results in a "saved successfully" message.

**Comment by rixx** [comment]
Since I cannot replicate the issue, I suspect it has been fixed and their instance is running an older pretalx version. I'm closing the issue on that basis – but I'll re-open it if new information comes to light!

**Comment by katrinleinweber** [comment]
Yeah, the GUI looks a bit older.
