### ISSUE TITLE
Offer 'anywhere in the world' deadline setting

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#81]
A recently popular deadline is "As long as it is October 15th, anywhere on the planet".

**Comment by gheesch** [comment]
wouldn't that be identical to October 16th 11:59:59 UTC?
since UTC-12 is the latest time zone at the moment.
should that be displayed for submissions as well as cfps? imo this would be a detriment to usability.

**Comment by rixx** [comment]
What do you mean "for submissions"?

This is just meant to affect the deadline display.

**Comment by gheesch** [comment]
so essentialy src/pretalx/cfp/templates/cfp/event/index.html line 12?

my thought was: if the organizer wants to set a deadline in this style (saving timezone hassle) one might want to store it as mentioned above and not change anything for display, since "11:59am where you are" has more utility than "midnight on the other side of the world" imo

**Comment by rixx** [comment]
It's not "midnight on the other side of the world"; it's "as long as it is <date>" – since displaying a countdown towards the end is something we ought to do anyways, that would clear things up sufficiently in my opinion.

**Comment by rixx** [comment]
By adding per-SubmissionType deadlines, this grew too complex to be easily done. Won't fix, unless somebody comes up with a comprehensive, intuitive solution.
