### ISSUE TITLE
update general settings with custom domain set triggers error

### ISSUE THREAD

**Issue by gislars** [pretalx/pretalx#853]
![pretalx_error](https://user-images.githubusercontent.com/402166/72189712-e0d4b400-33fd-11ea-9c50-e66a03fc704a.png)
## Current Behavior
In general setting page a custom domain is used.
If I want to change the orga address, an error message pops up

"Diese Domain wird schon für eine andere Veranstaltung verwendet." 

I have to empty the custom domain, save the page, change the orga address, put custom domain back in and save again.

## Expected Behavior
It should e possible to change the orga address when a custom domain is configured.
Also, I guess the error message is misleading since I only have one event configured.

## Steps to Reproduce

1. open general settings
2. make sure a custom domain is set and saved
3. change orga address 
4. save form -> error message appears 

## Context

Changing orga address is cumbersome, since the setting page needs to be changed and saved twice.

## Your Environment

* Version used: hosted version at pretalx.com
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 72.0.1 (64-Bit) Linux Mint
* Operating System and version (desktop or mobile): desktop
* Link to your instance, if in production:

**Comment by rixx** [comment]
The error message you are seeing is only shown if the custom domain is already in use for a different event, so there must be something else going on.

If you want to configure a custom event domain for a hosted event at pretalx.com, please get in touch via support@pretalx.com first, since this requires correct ssl certificates to be generated.
