### ISSUE TITLE
Have read-only fields and fields visible only for the organizers

### ISSUE THREAD

**Issue by eriktews** [pretalx/pretalx#910]
## Problem you are facing

We would like to use Pretalx to manage a budget for the speakers as well.

## Possible Solution

It would be great when we could have fields that are read-only for the speaker and maybe also fields that are only visible for the organizers.

When signals could be sent to plugins when the fields are updates, that would be great as well.

## Context

For example, we may want to have three fields: "requested amount", "accepted amount" and "receipt checked". In the field "requested amount", the speaker enters how many Euros he probably needs to come to zhe conference. (that's already implemented) In the field "accepted amount", we may then enter how many Euros we grant him to come to the conference. The field should be read-only for the speaker, but can be edited by the organizers. We then use the field "receipt checked" to indicate whether we have received a proper receipt from the speaker, but that is supposed to be used only for the organizers and does not need to be visible for the speaker.

When a signal could be sent to a custom plugin once a fields is updated, this would allow users to update a dashboard or trigger other actions as well.

**Comment by rixx** [comment]
By "fields", do you mean the questions/answers system?

I have the feeling that this may be out of scope to run within pretalx, and it may be better to implement it in a plugin – but I'm not quite clear on how you'd like this feature to be included in pretalx.

**Comment by eriktews** [comment]
I think this could be split. Pretalx might just support questions that can only be edited/answered by the conference organizers. I'm not so sure whether this can be implemented as a plugin using the current API.

Then you could implement a plugin that processes those answers further or aggregates the answers somehow.

**Comment by rixx** [comment]
To me, this really looks like plugin territory, since it would replicate noticeable functionality from issue trackers etc. Mixing sensitive and/or write-protected data with an API that is not meant to include them is tricky to get right.

I'm open for a more detailed proposal, but I've heard the request for an expenses plugin for pretalx before, so I suspect that that might be the better direction.

**Comment by rixx** [comment]
I'm closing this issue for now – open issues serve as a tracker for current efforts or planned features or immediate bugs, and this issue is currently a bit too nebulous to be productive. I'm more than happy to re-open it once the feature gets clearer, or to split it up into smaller, more defined issues.

Additionally, I've added your idea to our [plugin ideas](https://github.com/pretalx/pretalx/wiki/Plugin-ideas) wiki page, so that it's not forgotten and easier to find in the future.
