### ISSUE TITLE
Be clear about timezones

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#924]
## Current Behavior

The "select your available time" dialogs do not display any timezone by default.

## Expected Behavior

The schedule should be in the viewer's local timezone, and clearly be stated as such.

Alternatively, the schedule should be in the event's timezone, and clearly be stated as such.

## Context

This is currently a problem for our virtual event, where people are confused which timezone the dialogs are referring to. In the schedule speakers see when they submit their talk, it can be added to the description, but I haven't found a way to add it to the schedule speakers see when they confirm their talk.

I haven't checked the schedule views at all, but also there, all of them should be in the viewer's timezone, or less ideally, state that they are in the event's timezone, or ideally, both.

**Comment by rixx** [comment]
Good point! Currently, all times are always in the event timezone – pretalx is more used to physical events, where conforming to the browser timezone over the event timezone is downright dangerous, especially for travelling speakers or people lookign at the schedule upfront before travelling.

Of course, that's terrible UX for distributed events! I'd be happy to help guide or implement a fix for this. Thoughts:

### UI

I have no idea how a good interface for this would look like. It needs to be easy to switch timezones, especially on the interactive availability elements you mentioned, and on the schedule display. At the same time, screen estate is limited (especially in the schedule view), so at the same time, this should be hidden after first information?

### Tests

A couple of tests would make me sleep easier – all times in and outside of tests are localised to event timezones atm, and seeing that this still works well with inputs in different timezones would be nice.

## Implementation

The technical implementation isn't a big deal. Timezones are set [here](https://github.com/pretalx/pretalx/blob/master/src/pretalx/common/middleware/event.py#L148), so all we'd need to add is session information if this user prefers their own timezone, and also put this information into our templates, so that we can show/hide helpful hints in the schedule view.

**Comment by oxinabox** [comment]
A good start for this would be to display the event timezone in bold, the text above where speakers confirm what days they are available.
I have had like half a dozen people ask me what timezone that availability section is in
