### ISSUE TITLE
Pretalx Mail Filtering System Issue

### ISSUE THREAD

**Issue by spearr** [pretalx/pretalx#930]
## Current Behavior
When sending out emails based on specific submission types (through Pretalx Mail), emails were sent out for submission types that were not selected. Additionally, when 'All accepted speakers (who have not confirmed their talk yet)' is selected for Recipient Groups, speakers who already confirmed their submission also received emails.

## Expected Behavior
Emails should only be sent out for the selected submission types under 'All submissions of these types' and to the selected recipient group.

## Steps to Reproduce

1. Under 'Recipient Groups' select 'All accepted speakers (who have not confirmed their talk yet)'.
2. Under 'All submissions of these types' select 'Talk', 'Lightning Talk', and 'Birds of Feather' (for this specific case, at least).
3. Write and send emails.

## Context
This is used to send out emails to people who have not confirmed their submissions for JuliaCon 2020. It has created confusion for the speakers who did confirm since they received emails saying that they have not confirmed. Additionally, it has confused people that have submissions for types that have not had more information released, i.e. people with submission types that should not have received that email.

## Your Environment
The emails were sent using Pretalx through Chrome 81 on a Windows PC.

**Comment by oxinabox** [comment]
@spearr I recall you took screenshots before clicking send so you could double check that it was the right settings. I guess can upload here.

This is a really annoying one, since 25ish people should have been emailed to saying "You have not confirmed" and instead 200 were.
And when we went to sent a clarification that also went to the wrong people.

**Comment by rixx** [comment]
Yes, I'm afraid this is a limitation of the current email system – it ORs the email filters instead of ANDing them. I know it sucks, and I'm sorry you had trouble with it. It's easy to overlook additional recipients in the outbox :\

A big rewrite of the email feature in general is planned for this year, tracking in #753.
It was meant to be finished in the first half of the year, but then everything broke down, especially event industry related things, and so we're a bit late. It's the most urgent big feature on the roadmap, though, so it won't be long now, hopefully.
