### ISSUE TITLE
Select language for exports by URL

### ISSUE THREAD

**Issue by v0tti** [pretalx/pretalx#947]
## Problem you are facing

The language of schedule exports (iCal and frab compatible) formats only seems to be configurable by the request header.
This leads to unexpected behavior when using the export URL in Scripts and other software that depends on consistent results.

## Possible Solution

Make the language selectable via the path (e.g. `.../schedule/de/export/schedule.xml` for the German version).

## Context

This seems to be similar to #279.
I experienced this problem while configuring the c3voc streaming website. It assigns streams to schedule rooms. In my case the room names were different for German and English. My local version was English and that's how i configured the room filters, but the script on the server downloaded the German version.

**Comment by rixx** [comment]
Thank you for bringing this up!

I'm hesitant to change the URL to the schedule exports – we would have to either maintain multiple paths, or maintain reliable redirects, which is made all the harder because exporters can be provided by plugins.

At the same time, it would be fairly easy to accept a ``?lang=de`` queryparameter. Would that work for you, or am I overlooking limitations of adding language specification this way?

**Comment by v0tti** [comment]
> At the same time, it would be fairly easy to accept a `?lang=de` queryparameter. Would that work for you, or am I overlooking limitations of adding language specification this way?

I do not see any reason why this would not work.
