### ISSUE TITLE
Non-admin can't see Items that are linked but are not scheduled.

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#956]
## Problem you are facing
I have a list of linked to items that are not on the schedule,
but that i want people to be able to read.
For example one of the many links in [this list](https://pretalx.com/juliacon2020/talk/9BNNMD/), is to  [this page](https://pretalx.com/juliacon2020/talk/3CEUF7/)

I (having admin privs), can read them without issue (and I therefore thought everything was fine.
But it turns out that only i can see them, for everyone else (including the authors) the page 404s.
I thought turing on sneak-peak would fix this.
But it didn't.

## Possible Solution
Make sneakpeak allow the talk page to always be visable, regardless of if the event is now public and regardless of if it appears in the program.

## Context

JuliaCon uses Pretalx for the review process of posters as well as  scheduled talks.
Posters do not occur at a specific time, but rather in a poster sesssion,
which occupies a room for 1.5 hours.

So we just put in a program item called Poster Session,
and then we put in a list of all the items that are during it.
And since i found the talk pages worked (for me), I thought better yet, I can link to those pages and then people will see the descriptions and everything.
(Last year we did not link to the pages, we just gave the title and the author).

We don't want to put them in the schedule because:
 1. it would confuse people into thinking they were at a particular time
 2. having 18 items in 1.5 hour block would be unreadable. (Per other issues having 9 items in a 1.5 hour block is almost unreable)

**Comment by rixx** [comment]
That's a use case I hadn't considered, but that's a really good point. Definitely something we should fix.

**Comment by oxinabox** [comment]
I think the fix isn't too hard?

I think it might be changing something in the boolean logic in:
https://github.com/pretalx/pretalx/blob/86b3ad07209dde213aa6b0faf3c2b5b08c06b630/src/pretalx/agenda/permissions.py

Do you think we might be able to have it for the JuliaCon instance in the next few weeks?
Otherwise we are going to have to deploy a bunch of static pages on our website that are going to go out of date when people update their talk descriptions.

**Comment by rixx** [comment]
Should be absolutely doable, just give me a couple of days – I have prior obligations that I have to get done first.

**Comment by rixx** [comment]
Hm, the problem with your suggested solution is that currently the sneak peek feature does not link to talk detail pages – it is, after all, only a "peek", not a complete preview. Making all talk information available seems invasive and would break backwards compatibility and potentially introduce privacy issues, because organisers do not assume full talk details to become available this way.

The best alternative I can see would be the hidden talk review pages. They are meant to allow submitters to solicit feedback from others by providing a read-only view on the submission. They look pretty much exactly like the talk pages (though currently the speaker link may 404, sadly). Would that work for you? I just pushed a change that shows you the link to the secret talk page on the submission page, like this:
![2020-07-05T03:02+02:00](https://user-images.githubusercontent.com/2657547/86523400-241f5500-be6c-11ea-9c17-e5536a73a9a9.png)

**Comment by oxinabox** [comment]
Sounds like it would.
I will give it a try

**Comment by oxinabox** [comment]
How can I determine what the Secret Public URL is for a given submission?
I can't see it documented on the API page.

**Comment by oxinabox** [comment]
@rixx did you see my question above?

**Comment by rixx** [comment]
There is currently no field in the API to expose the secret URL.

**Comment by oxinabox** [comment]
Ok I guess I can just spend 15mins copy pasting

**Comment by oxinabox** [comment]
Ooh I can us selenium again

**Comment by oxinabox** [comment]
Selenium for my own future reference:
```

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

browser = webdriver.Chrome()
url = "https://pretalx.com/orga/event/juliacon2020/"
browser.get(url)

def poster_line(code, author):
    sub_url = "https://pretalx.com/orga/event/juliacon2020/submissions/" + code
    browser.get(sub_url)
    btn_ele = browser.find_element_by_xpath("//*[@id=\"page-content\"]/main/ul/details")
    btn_ele.click()
    link_ele = browser.find_element_by_partial_link_text("Secret public link")
    url = link_ele.get_attribute("href")
    title_ele = browser.find_element_by_id("id_title")
    title = title_ele.get_attribute("value")
    return " - " + "[\"" + title + "\" by " + author + "](" + url+ ")"
```

**Comment by rixx** [comment]
An update because people are stumbling upon this old issue: There are two ways of showing sessions that are not scheduled (e.g. poster sessions):

1. Mark the sessions as featured, then link to the "featured sessions" page
2. Link to the "secret public page" / review page. Organisers can now use the REST API to retrieve the required code – it’s the value of the `review_code` field.
