### ISSUE TITLE
Item which says in schedule editor it goes for 210min shows as going forr 200min in schdule

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#960]
## Current Behavior

In schedule editor i see something starting at 14:00 and going for 210 minutes
So it should finish at 17:30.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/5127634/86515292-c0673e80-be0f-11ea-9d7b-02ea1e6898b7.png">

In the schedule i see it starting at 14:00 but finishing at 17:20
<img width="799" alt="image" src="https://user-images.githubusercontent.com/5127634/86515344-1cca5e00-be10-11ea-82a4-272a6d6df33d.png">

Similar in the talk's page it say 14:00 finishing at 17:20
https://pretalx.com/juliacon2020/talk/GQATHR/

## Expected Behavior

Everything to say it finishs at 17:30.

## Steps to Reproduce
I have no idea but it has happend to a bunch of out JuliaCon program items
Lightgraphs, BinaryBuilder, Sciml, Wrapping C++, DataFrames, MLJ, Make your code faster 
 all come up as 14-17.20, but also say they are 210 minutes long

## Context
Our published schedule is wrong and will confuse attendees as to when things finish.
A schedule thed reflect what is planned to to happen would be most useful.

## Your Environment

* Version used: unknown
* Environment name and version (e.g. Chrome 39, python 3.5):  Firefox 77.0.1 
* Operating System and version (desktop or mobile): Desktop, Mac OS X 10.15.5
* Link to your instance, if in production: https://pretalx.com/orga/event/juliacon2020/

**Comment by rixx** [comment]
> A schedule thed reflect what is planned to to happen would be most useful.

I appreciate your frustration as well as your snark.

All submissions concerned by this bug, 11 in total, belong to the same submission type. I assume this must have happened when the duration of the submission type in question was changed in the past? This was a known bug for a time, although it should have been fixed by now.

I'm not sure how this happened and I cannot seem to reproduce it. I fixed the workshops in question manually (feel free to approach support@pretalx.com with support requests like this in the future). I will close this issue until there's a way to reproduce it.

**Comment by oxinabox** [comment]
Thanks.

> I appreciate your frustration as well as your snark.

Sorry, the snark was a bit much.
I was having trouble filling in the template. I probably should have just lefts that there.


>  I assume this must have happened when the duration of the submission type in question was changed in the past?

That is my theory also.
I feel like I have run into this before, but I couldn't find an issue I raised about it then, so assumed it was with other conference software
