### ISSUE TITLE
SMTP Password field visibility

### ISSUE THREAD

**Issue by momorientes** [pretalx/pretalx#994]
## Current Behavior
When reviewing E-Mail settings the Password field is currently displayed empty even if a valid password is stored.

## Expected Behavior

If no password is stored the field should be empty, if a password is stored it should be indicated that a value has been set (i.e. by displaying a sequence of asterisks)

## Steps to Reproduce

1. Go to E-Mail Settings for an event
2. enter a smtp password & save

## Context

We often copy from previous events and it's never clear if the password has been correctly copied or not (or if it is our mailserver acting up).

**Comment by chriswolfdesign** [comment]
I'm very new at open source so I'm a bit nervous about offering, but I could try to handle this one if you would like?

**Comment by rixx** [comment]
Sure!

To set up pretalx, you can follow the [developmtent setup guide](https://docs.pretalx.org/developer/setup.html). Then, you will want to look at the email settings form – the form definition can be found in `pretalx/orga/forms/event.py` as `MailSettingsForm`. I think the best idea would be to override the `placeholder` of the `smtp_password` field to something like `************` if an SMTP password is already set, and leave it unchanged otherwise. Let me know if you need any help on the way!

(The reason that this is necessary is that this settings form can be accessed by every organiser, but we don't want to leak the email password between them, so we don't actually expose the password here.)

**Comment by chriswolfdesign** [comment]
Great, I work a full time software development job so I may not be able to get around to it until this weekend but I'd really like to start contributing to projects.  Quick question about the expectation.  Do we want the number of asterisks to fit the length of the password?  So if the password was "foo" would we want the password to display as ***?  Or do we want the length of the asterisks to be the same, regardless of the length of the password?

**Comment by rixx** [comment]
We should keep the number of asterisks constant, to avoid leaking any information about the password.

**Comment by chriswolfdesign** [comment]
Sorry this took longer than I had expected to get back to you guys.  I had some unexpected guests this weekend.  I have finished the functionality but I have a few concerns.  First, whenever I run existing tests these two fail:

* test_agenda_schedule_export: test_html_export_language
* test_cfp_user: test_can_change_locale

I'm not sure how to go about making those two tests pass and I'm also not sure how to go about unit testing my own code I wrote.  I'm still quite new at Django.  Could anybody provide a bit of guidance on these topics?  Sorry for any inconvenience.

**Comment by rixx** [comment]
Since the tests don't fail in our CI, you can probably ignore them. It will be due to your local setup and available locales – don't worry about it. We will see if CI still passes (which I assume) if you open a PR.

**Comment by chriswolfdesign** [comment]
I just pushed but sadly two tests did fail in the CI.

**Comment by rixx** [comment]
All tests, including style tests, are passing – nice work! The one failing check is the coverage, but that's not your fault – we seem to be missing a test for updating the email settings, so the patch coverage is comparatively low. Nothing to worry about. Thank you for contributing to pretalx!
